In [51]:
import pandas as pd
from datetime import date, timedelta
from datetime import datetime
import os
import shutil
import pathlib
from nbconvert import PythonExporter
import polars as pl
import glob
import time

In [52]:
def convert_to_datetime(struct_time):
    return datetime(*struct_time[:6])


def input_data(data_dir):
    """Read all xlsx/csv files in a directory into a single Polars DataFrame."""
    
    def read_file(filename):
        try:
            mtime = convert_to_datetime(time.localtime(os.path.getmtime(filename)))
            df = (pl.read_excel(filename, infer_schema_length=0) if filename.suffix.lower() == '.xlsx'
                  else pl.read_csv(filename, infer_schema_length=0,
                                   encoding='utf-8' if True else 'ISO-8859-1'))
            return df.with_columns(pl.lit(filename.stem).alias('sheet_name'),
                                   pl.lit(mtime).alias('Export time'))
        except Exception:
            try:
                return (pl.read_csv(filename, infer_schema_length=0,
                                    encoding='ISO-8859-1', ignore_errors=True)
                        .with_columns(pl.lit(filename.stem).alias('sheet_name'),
                                      pl.lit(mtime).alias('Export time')))
            except Exception as e:
                print(f"Error reading {filename}: {e}")
                return None

    dfs = [df for f in pathlib.Path(data_dir).glob('**/*.*')
           if f.suffix.lower() in ('.xlsx', '.csv') and (df := read_file(f)) is not None]
    
    if not dfs:
        return pl.DataFrame()

    col_dtypes = {col: {df[col].dtype for df in dfs if col in df.columns}
                  for col in set(col for df in dfs for col in df.columns)}
    dfs = [df.with_columns(pl.col(c).cast(pl.Utf8)
                           for c, t in col_dtypes.items() if c in df.columns and len(t) > 1)
           for df in dfs]

    return pl.concat(dfs, how='vertical')

In [53]:
notebook_dict = {
  'IEX_optimized.ipynb': 1,
  'RTA_optimized (1).ipynb': 1,
}

def convert_notebook(notebook_path):
    exporter = PythonExporter()
    output, _ = exporter.from_filename(notebook_path)
    return output

first_glob = os.path.expanduser("~").replace("\\", "/")
test_path  = f'{first_glob}/Concentrix Corporation'
if not os.path.exists(test_path):
    raise FileNotFoundError(f'Not found the path: {test_path}')

folder_paths = {
    'output_iex_base'     : f'{first_glob}/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/OUTPUT_AGENT_IEX_BASE'
}

print(f"Currently using base directory: {first_glob}")
IEX_BASE = input_data(folder_paths['output_iex_base'])
IEX_BASE

Currently using base directory: C:/Users/ADMIN

shape: (83_497, 10)
┌─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬────────┐
│ Agent   ┆ Date    ┆ Start_S ┆ End_Shi ┆ Schedul ┆ Start_A ┆ End_Act ┆ sheet_n ┆ Export  ┆ Genera │
│ ---     ┆ ---     ┆ hift    ┆ ft      ┆ ed Acti ┆ ction   ┆ ion     ┆ ame     ┆ time    ┆ te     │
│ str     ┆ str     ┆ ---     ┆ ---     ┆ vity    ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ Date   │
│         ┆         ┆ str     ┆ str     ┆ ---     ┆ str     ┆ str     ┆ str     ┆ datetim ┆ ---    │
│         ┆         ┆         ┆         ┆ str     ┆         ┆         ┆         ┆ e[μs]   ┆ str    │
╞═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪════════╡
│ Agent:  ┆ 2026-01 ┆ 9:00 PM ┆ 10:00   ┆ Break   ┆ 10:15   ┆ 10:30   ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -05     ┆         ┆ AM      ┆         ┆ PM      ┆ PM      ┆ e_2026_ ┆ -26 11: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 20:33   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 9:00 PM ┆ 10:00   ┆ Open    ┆ 10:30   ┆ 2:30 AM ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -05     ┆         ┆ AM      ┆ Time    ┆ PM      ┆         ┆ e_2026_ ┆ -26 11: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 20:33   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 9:00 PM ┆ 10:00   ┆ Lunch   ┆ 2:30 AM ┆ 3:30 AM ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -05     ┆         ┆ AM      ┆         ┆         ┆         ┆ e_2026_ ┆ -26 11: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 20:33   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 9:00 PM ┆ 10:00   ┆ Open    ┆ 3:30 AM ┆ 4:30 AM ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -05     ┆         ┆ AM      ┆ Time    ┆         ┆         ┆ e_2026_ ┆ -26 11: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 20:33   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 9:00 PM ┆ 10:00   ┆ Break   ┆ 4:30 AM ┆ 4:45 AM ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -05     ┆         ┆ AM      ┆         ┆         ┆         ┆ e_2026_ ┆ -26 11: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 20:33   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 9:00 PM ┆ 10:00   ┆ Open    ┆ 4:45 AM ┆ 6:00 AM ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -05     ┆         ┆ AM      ┆ Time    ┆         ┆         ┆ e_2026_ ┆ -26 11: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 20:33   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 9:00 PM ┆ 10:00   ┆ Extra   ┆ 6:00 AM ┆ 7:45 AM ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -05     ┆         ┆ AM      ┆ Hours   ┆         ┆         ┆ e_2026_ ┆ -26 11: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 20:33   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 9:00 PM ┆ 10:00   ┆ Break   ┆ 7:45 AM ┆ 8:00 AM ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -05     ┆         ┆ AM      ┆         ┆         ┆         ┆ e_2026_ ┆ -26 11: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 20:33   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 9:00 PM ┆ 10:00   ┆ Extra   ┆ 8:00 AM ┆ 10:00   ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -05     ┆         ┆ AM      ┆ Hours   ┆         ┆ AM      ┆ e_2026_ ┆ -26 11: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 20:33   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 9:00 PM ┆ 10:00   ┆ Open    ┆ 9:00 PM ┆ 10:15   ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -05     ┆         ┆ AM      ┆ Time    ┆         ┆ PM      ┆ e_2026_ ┆ -26 11: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 20:33   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 6:00 PM ┆ 7:00 AM ┆ Break   ┆ 10:15   ┆ 10:30   ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -06     ┆         ┆         ┆         ┆ PM      ┆ PM      ┆ e_2026_ ┆ -26 11: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 20:33   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 6:00 PM ┆ 7:00 AM ┆ Open    ┆ 10:30   ┆ 1:15 AM ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -06     ┆         ┆         ┆ Time    ┆ PM      ┆         ┆ e_2026_ ┆ -26 11: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 20:33   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 6:00 PM ┆ 7:00 AM ┆ Lunch   ┆ 1:15 AM ┆ 2:15 AM ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -06     ┆         ┆         ┆         ┆         ┆         ┆ e_2026_ ┆ -26 11: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 20:33   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 6:00 PM ┆ 7:00 AM ┆ Open    ┆ 2:15 AM ┆ 4:30 AM ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -06     ┆         ┆         ┆ Time    ┆         ┆         ┆ e_2026_ ┆ -26 11: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 20:33   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 6:00 PM ┆ 7:00 AM ┆ Break   ┆ 4:30 AM ┆ 4:45 AM ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -06     ┆         ┆         ┆         ┆         ┆         ┆ e_2026_ ┆ -26 11: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 20:33   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 6:00 PM ┆ 7:00 AM ┆ Open    ┆ 4:45 AM ┆ 6:00 AM ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -06     ┆         ┆         ┆ Time    ┆         ┆         ┆ e_2026_ ┆ -26 11: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 20:33   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 6:00 PM ┆ 7:00 AM ┆ Extra   ┆ 6:00 AM ┆ 7:00 AM ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -06     ┆         ┆         ┆ Hours   ┆         ┆         ┆ e_2026_ ┆ -26 11: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 20:33   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 6:00 PM ┆ 7:00 AM ┆ Extra   ┆ 6:00 PM ┆ 7:15 PM ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -06     ┆         ┆         ┆ Hours   ┆         ┆         ┆ e_2026_ ┆ -26 11: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 20:33   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 6:00 PM ┆ 7:00 AM ┆ Break   ┆ 7:15 PM ┆ 7:30 PM ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -06     ┆         ┆         ┆         ┆         ┆         ┆ e_2026_ ┆ -26 11: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 20:33   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 6:00 PM ┆ 7:00 AM ┆ Extra   ┆ 7:30 PM ┆ 9:00 PM ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -06     ┆         ┆         ┆ Hours   ┆         ┆         ┆ e_2026_ ┆ -26 11: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 20:33   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 6:00 PM ┆ 7:00 AM ┆ Open    ┆ 9:00 PM ┆ 10:15   ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -06     ┆         ┆         ┆ Time    ┆         ┆ PM      ┆ e_2026_ ┆ -26 11: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 20:33   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 8:30 PM ┆ 4:30 AM ┆ Break   ┆ 10:00   ┆ 10:15   ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -07     ┆         ┆         ┆         ┆ PM      ┆ PM      ┆ e_2026_ ┆ -26 11: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 20:33   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 8:30 PM ┆ 4:30 AM ┆ Extra   ┆ 10:15   ┆ 1:15 AM ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -07     ┆         ┆         ┆ Hours   ┆ PM      ┆         ┆ e_2026_ ┆ -26 11: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 20:33   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 8:30 PM ┆ 4:30 AM ┆ Break   ┆ 1:15 AM ┆ 1:30 AM ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -07     ┆         ┆         ┆         ┆         ┆         ┆ e_2026_ ┆ -26 11: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 20:33   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 8:30 PM ┆ 4:30 AM ┆ Extra   ┆ 1:30 AM ┆ 4:30 AM ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -07     ┆         ┆         ┆ Hours   ┆         ┆         ┆ e_2026_ ┆ -26 11: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 20:33   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ …       ┆ …       ┆ …       ┆ …       ┆ …       ┆ …       ┆ …       ┆ …       ┆ …       ┆ …      │
│ Agent:  ┆ 2026-07 ┆ 5:00 AM ┆ 2:00 PM ┆ Lunch   ┆ 9:15 AM ┆ 10:15   ┆ IEX_Bas ┆ 2026-07 ┆ 7/2/26 │
│ 3109551 ┆ -06     ┆         ┆         ┆         ┆         ┆ AM      ┆ e_2026_ ┆ -02 11: ┆ 4:22   │
│ Hoang,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 07_06   ┆ 45:51   ┆ AM     │
│ DaiHai  ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-07 ┆ null    ┆ null    ┆ Off     ┆ null    ┆ null    ┆ IEX_Bas ┆ 2026-07 ┆ 7/2/26 │
│ 3109643 ┆ -06     ┆         ┆         ┆         ┆         ┆         ┆ e_2026_ ┆ -02 11: ┆ 4:22   │
│ Tran,   ┆         ┆         ┆         ┆         ┆         ┆         ┆ 07_06   ┆ 45:51   ┆ AM     │
│ DucTin  ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-07 ┆ 1:00 PM ┆ 10:00   ┆ Open    ┆ 1:00 PM ┆ 4:00 PM ┆ IEX_Bas ┆ 2026-07 ┆ 7/2/26 │
│ 3109794 ┆ -06     ┆         ┆ PM      ┆ Time    ┆         ┆         ┆ e_2026_ ┆ -02 11: ┆ 4:22   │
│ Tran,   ┆         ┆         ┆         ┆         ┆         ┆         ┆ 07_06   ┆ 45:51   ┆ AM     │
│ ChauBao ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Ye…     ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-07 ┆ 1:00 PM ┆ 10:00   ┆ Break   ┆ 4:00 PM ┆ 4:15 PM ┆ IEX_Bas ┆ 2026-07 ┆ 7/2/26 │
│ 3109794 ┆ -06     ┆         ┆ PM      ┆         ┆         ┆         ┆ e_2026_ ┆ -02 11: ┆ 4:22   │
│ Tran,   ┆         ┆         ┆         ┆         ┆         ┆         ┆ 07_06   ┆ 45:51   ┆ AM     │
│ ChauBao ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Ye…     ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-07 ┆ 1:00 PM ┆ 10:00   ┆ Open    ┆ 4:15 PM ┆ 6:15 PM ┆ IEX_Bas ┆ 2026-07 ┆ 7/2/26 │
│ 3109794 ┆ -06     ┆         ┆ PM      ┆ Time    ┆         ┆         ┆ e_2026_ ┆ -02 11: ┆ 4:22   │
│ Tran,   ┆         ┆         ┆         ┆         ┆         ┆         ┆ 07_06   ┆ 45:51   ┆ AM     │
│ ChauBao ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Ye…     ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-07 ┆ 1:00 PM ┆ 10:00   ┆ Lunch   ┆ 6:15 PM ┆ 7:15 PM ┆ IEX_Bas ┆ 2026-07 ┆ 7/2/26 │
│ 3109794 ┆ -06     ┆         ┆ PM      ┆         ┆         ┆         ┆ e_2026_ ┆ -02 11: ┆ 4:22   │
│ Tran,   ┆         ┆         ┆         ┆         ┆         ┆         ┆ 07_06   ┆ 45:51   ┆ AM     │
│ ChauBao ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Ye…     ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-07 ┆ 1:00 PM ┆ 10:00   ┆ Open    ┆ 7:15 PM ┆ 8:45 PM ┆ IEX_Bas ┆ 2026-07 ┆ 7/2/26 │
│ 3109794 ┆ -06     ┆         ┆ PM      ┆ Time    ┆         ┆         ┆ e_2026_ ┆ -02 11: ┆ 4:22   │
│ Tran,   ┆         ┆         ┆         ┆         ┆         ┆         ┆ 07_06   ┆ 45:51   ┆ AM     │
│ ChauBao ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Ye…     ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-07 ┆ 1:00 PM ┆ 10:00   ┆ Break   ┆ 8:45 PM ┆ 9:00 PM ┆ IEX_Bas ┆ 2026-07 ┆ 7/2/26 │
│ 3109794 ┆ -06     ┆         ┆ PM      ┆         ┆         ┆         ┆ e_2026_ ┆ -02 11: ┆ 4:22   │
│ Tran,   ┆         ┆         ┆         ┆         ┆         ┆         ┆ 07_06   ┆ 45:51   ┆ AM     │
│ ChauBao ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Ye…     ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-07 ┆ 1:00 PM ┆ 10:00   ┆ Open    ┆ 9:00 PM ┆ 10:00   ┆ IEX_Bas ┆ 2026-07 ┆ 7/2/26 │
│ 3109794 ┆ -06     ┆         ┆ PM      ┆ Time    ┆         ┆ PM      ┆ e_2026_ ┆ -02 11: ┆ 4:22   │
│ Tran,   ┆         ┆         ┆         ┆         ┆         ┆         ┆ 07_06   ┆ 45:51   ┆ AM     │
│ ChauBao ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Ye…     ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-07 ┆ null    ┆ null    ┆ Off     ┆ null    ┆ null    ┆ IEX_Bas ┆ 2026-07 ┆ 7/2/26 │
│ 3110171 ┆ -06     ┆         ┆         ┆         ┆         ┆         ┆ e_2026_ ┆ -02 11: ┆ 4:22   │
│ Nguyen, ┆         ┆         ┆         ┆         ┆         ┆         ┆ 07_06   ┆ 45:51   ┆ AM     │
│ NgocHoa ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ …       ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-07 ┆ null    ┆ null    ┆ Off     ┆ null    ┆ null    ┆ IEX_Bas ┆ 2026-07 ┆ 7/2/26 │
│ 3112779 ┆ -06     ┆         ┆         ┆         ┆         ┆         ┆ e_2026_ ┆ -02 11: ┆ 4:22   │
│ Nguyen, ┆         ┆         ┆         ┆         ┆         ┆         ┆ 07_06   ┆ 45:51   ┆ AM     │
│ QuocHun ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ …       ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-07 ┆ 1:00 PM ┆ 10:00   ┆ Open    ┆ 1:00 PM ┆ 2:30 PM ┆ IEX_Bas ┆ 2026-07 ┆ 7/2/26 │
│ 3112804 ┆ -06     ┆         ┆ PM      ┆ Time    ┆         ┆         ┆ e_2026_ ┆ -02 11: ┆ 4:22   │
│ Nguyen, ┆         ┆         ┆         ┆         ┆         ┆         ┆ 07_06   ┆ 45:51   ┆ AM     │
│ ThiThuT ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ …       ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-07 ┆ 1:00 PM ┆ 10:00   ┆ Break   ┆ 2:30 PM ┆ 2:45 PM ┆ IEX_Bas ┆ 2026-07 ┆ 7/2/26 │
│ 3112804 ┆ -06     ┆         ┆ PM      ┆         ┆         ┆         ┆ e_2026_ ┆ -02 11: ┆ 4:22   │
│ Nguyen, ┆         ┆         ┆         ┆         ┆         ┆         ┆ 07_06   ┆ 45:51   ┆ AM     │
│ ThiThuT ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ …       ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-07 ┆ 1:00 PM ┆ 10:00   ┆ Open    ┆ 2:45 PM ┆ 4:15 PM ┆ IEX_Bas ┆ 2026-07 ┆ 7/2/26 │

In [54]:
for nbook in notebook_dict:
    if notebook_dict[nbook] == 0:
        print(f"Not executing notebook {nbook}.")
        continue
        
    nbook_path = f'{first_glob}/Concentrix Corporation/WFM-Expedia-HCM - Branding files/BI_Task/CODE/Python_Code/{nbook}'
    
    if os.path.isfile(nbook_path):
        print(f"Running notebook: {nbook}")
        try:
            script = convert_notebook(nbook_path)
            exec(script)
        except Exception as e:
            print(f"Error running notebook: {nbook}")
            print(str(e))
    else:
        print(f"Error: Notebook {nbook} not found.")

Running notebook: IEX_optimized.ipynb
--- FULL FOLDER PATHS LIST ---
input_iex: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/INPUT_AGENT_IEX_FOR_REPORT
input_hc_master: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Headcount/HC Master Database - 2026.xlsx
output_iex: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/OUTPUT_AGENT_IEX_FOR_REPORT
output_iex_all: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/STORAGE_OUTPUT_AGENT_IEX
output_iex_intervals: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/OUTPUT_AGENT_IEX_INTERVALS
output_iex_base: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/OUTPUT_AGENT_IEX_BASE
hc_extend_by_month: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Headcount/HC Extend by Month
input_iex_schedule_adjustment: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/IEX Backdated Schedule Adjustment Log.xlsx

<string>:268: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
<string>:302: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.

✅ Exported 15 file(s) to 'C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/OUTPUT_AGENT_IEX_BASE':
   IEX_Base_2026_03_09.csv  (2 rows)
   IEX_Base_2026_03_16.csv  (13 rows)
   IEX_Base_2026_03_23.csv  (4 rows)
   IEX_Base_2026_03_30.csv  (3 rows)
   IEX_Base_2026_04_27.csv  (1 rows)
   IEX_Base_2026_05_04.csv  (3800 rows)
   IEX_Base_2026_05_11.csv  (3496 rows)
   IEX_Base_2026_05_18.csv  (4093 rows)
   IEX_Base_2026_05_25.csv  (4254 rows)
   IEX_Base_2026_06_01.csv  (4966 rows)
   IEX_Base_2026_06_08.csv  (4998 rows)
   IEX_Base_2026_06_15.csv  (5108 rows)
   IEX_Base_2026_06_22.csv  (4607 rows)
   IEX_Base_2026_06_29.csv  (5301 rows)
   IEX_Base_2026_07_06.csv  (684 rows)
Valid weeks found: ['2026-05-04', '2026-05-11', '2026-05-18', '2026-05-25', '2026-06-01', '2026-06-08', '2026-06-15', '2026-06-22', '2026-06-29']

<string>:353: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.

Rows after filter: 40623
Weeks retained: ['2026-05-04', '2026-05-11', '2026-05-18', '2026-05-25', '2026-06-01', '2026-06-08', '2026-06-15', '2026-06-22', '2026-06-29']

<string>:598: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
<string>:801: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.

=== STAGE 3: sorted_df rows ===

,Date,IEX_ID,Scheduled Activity,Datetime_Start_Action,Datetime_End_Action,First Shift,Open Time,Extra Time,NCNS,Target,Time_Of_Day,Shift Tracking
32899,2026-06-25,3110171,Extra Hours,2026-06-25 06:00:00,2026-06-25 07:00:00,2100-0600,7.5,1.0,0.0,8.5,9.0,PR - OT
32900,2026-06-25,3110171,Unscheduled,2026-06-25 07:00:00,2026-06-25 21:00:00,2100-0600,7.5,1.0,0.0,8.5,9.0,PR - OT
32901,2026-06-25,3110171,Open Time,2026-06-25 21:00:00,2026-06-26 00:15:00,2100-0600,7.5,1.0,0.0,8.5,9.0,PR - OT
32902,2026-06-25,3110171,Break_1,2026-06-26 00:15:00,2026-06-26 00:30:00,2100-0600,7.5,1.0,0.0,8.5,9.0,PR - OT
32903,2026-06-25,3110171,Open Time,2026-06-26 00:30:00,2026-06-26 02:00:00,2100-0600,7.5,1.0,0.0,8.5,9.0,PR - OT
32904,2026-06-25,3110171,Lunch,2026-06-26 02:00:00,2026-06-26 03:00:00,2100-0600,7.5,1.0,0.0,8.5,9.0,PR - OT
32905,2026-06-25,3110171,Open Time,2026-06-26 03:00:00,2026-06-26 04:40:00,2100-0600,7.5,1.0,0.0,8.5,9.0,PR - OT
32906,2026-06-25,3110171,Break_2,2026-06-26 04:40:00,2026-06-26 04:55:00,2100-0600,7.5,1.0,0.0,8.5,9.0,PR - OT
32907,2026-06-25,3110171,Open Time,2026-06-26 04:55:00,2026-06-26 06:00:00,2100-0600,7.5,1.0,0.0,8.5,9.0,PR - OT

=== STAGE 4: IEX_EXTEND rows (final output) ===

,Date,IEX_ID,Datetime_First_Start_Shift,Datetime_First_End_Shift,First Shift,Open Time,Extra Time,Target,Time_Of_Day,Shift Tracking
32899,2026-06-25,3110171,2026-06-25 21:00:00,2026-06-26 06:00:00,2100-0600,7.5,1.0,8.5,9.0,PR - OT

Valid weeks: [Timestamp('2026-05-04 00:00:00'), Timestamp('2026-05-11 00:00:00'), Timestamp('2026-05-18 00:00:00'), Timestamp('2026-05-25 00:00:00'), Timestamp('2026-06-01 00:00:00'), Timestamp('2026-06-08 00:00:00'), Timestamp('2026-06-15 00:00:00'), Timestamp('2026-06-22 00:00:00'), Timestamp('2026-06-29 00:00:00')]
Running notebook: RTA_optimized (1).ipynb
--- FULL FOLDER PATHS LIST ---
input_iex_rawdata: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/INPUT_AGENT_IEX_FOR_REPORT
storage_iex_rawdata: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/STORAGE_INPUT_AGENT_IEX
input_agent_activity: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/INPUT_AGENT_ACTIVITY_FOR_REPORT
storage_agent_activity: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/STORAGE_INPUT_AGENT_ACTIVITY
input_iex: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/OUTPUT_AGENT_IEX_FOR_REPORT
input_iex_intervals: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/OUTPUT_AGENT_IEX_INTERVALS
input_pull_out: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Save/EXP Leave Management.xlsx
input_ramco_code: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/INPUT_RAMCO_CODE
input_ramco_ot: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/INPUT_OT_RAMCO_CODE
output_rta: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/OUTPUT_RTA_FOR_REPORT
output_rta_all: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/STORAGE_OUTPUT_RTA
rta_intervals_output: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/OUTPUT_AGENT_ACTIVITY_INTERVALS
ramco_output: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata
hc_extend_by_month: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Headcount/HC Extend by Month
resources: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/BI_Task/CODE/Resources

Could not determine dtype for column 43, falling back to string
Could not determine dtype for column 43, falling back to string
Could not determine dtype for column 43, falling back to string
Could not determine dtype for column 43, falling back to string
Could not determine dtype for column 43, falling back to string
Could not determine dtype for column 43, falling back to string
Could not determine dtype for column 43, falling back to string
<string>:379: DeprecationWarning: `DataFrame.melt` is deprecated; use `DataFrame.unpivot` instead, with `index` instead of `id_vars` and `on` instead of `value_vars`

shape: (2_103, 7)
┌───────────┬────────────┬────────────────────┬───────┬───────────────┬──────────────┬─────────────┐
│ EID       ┆ Date       ┆ ot_type            ┆ hours ┆ nsa_authorize ┆ ot_authorize ┆ ot_status   │
│ ---       ┆ ---        ┆ ---                ┆ ---   ┆ ---           ┆ ---          ┆ ---         │
│ str       ┆ date       ┆ str                ┆ f64   ┆ str           ┆ str          ┆ str         │
╞═══════════╪════════════╪════════════════════╪═══════╪═══════════════╪══════════════╪═════════════╡
│ 103293732 ┆ 2026-01-10 ┆ OT2.0X: 1.0 hrs,   ┆ 7.0   ┆               ┆ Authorized   ┆ (7.0 hrs -  │
│           ┆            ┆ OT2.7X: 6.0 h…     ┆       ┆               ┆              ┆ Authorized) │
│ 103082121 ┆ 2026-05-19 ┆ NSA: 7.0 hrs,      ┆ 0.5   ┆ Authorized    ┆ Authorized   ┆ (0.5 hrs -  │
│           ┆            ┆ OT2.0X: 0.5 hrs    ┆       ┆               ┆              ┆ Authorized) │
│ 102884091 ┆ 2025-05-01 ┆ OT3.0X: 8.0 hrs    ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs -  │
│           ┆            ┆                    ┆       ┆               ┆              ┆ Authorized) │
│ 102484482 ┆ 2026-01-07 ┆ OT2.0X: 0.5 hrs,   ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs -  │
│           ┆            ┆ OT2.7X: 7.5 h…     ┆       ┆               ┆              ┆ Authorized) │
│ 102871040 ┆ 2026-01-10 ┆ OT2.0X: 5.5 hrs    ┆ 5.5   ┆               ┆ Authorized   ┆ (5.5 hrs -  │
│           ┆            ┆                    ┆       ┆               ┆              ┆ Authorized) │
│ 103145155 ┆ 2025-04-07 ┆ OT3.0X: 8.0 hrs    ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs -  │
│           ┆            ┆                    ┆       ┆               ┆              ┆ Authorized) │
│ 103304866 ┆ 2026-04-26 ┆ OT3.0X: 6.0 hrs    ┆ 6.0   ┆               ┆ Authorized   ┆ (6.0 hrs -  │
│           ┆            ┆                    ┆       ┆               ┆              ┆ Authorized) │
│ 103109336 ┆ 2026-04-30 ┆ OT3.0X: 1.0 hrs,   ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs -  │
│           ┆            ┆ OT3.9X: 7.0 h…     ┆       ┆               ┆              ┆ Authorized) │
│ 103085298 ┆ 2026-05-20 ┆ OT2.0X: 5.0 hrs,   ┆ 5.5   ┆               ┆ Authorized   ┆ (5.5 hrs -  │
│           ┆            ┆ OT2.7X: 0.5 h…     ┆       ┆               ┆              ┆ Authorized) │
│ 103130519 ┆ 2026-02-04 ┆ OT2.0X: 0.5 hrs    ┆ 0.5   ┆               ┆ Authorized   ┆ (0.5 hrs -  │
│           ┆            ┆                    ┆       ┆               ┆              ┆ Authorized) │
│ 103103198 ┆ 2025-04-30 ┆ OT3.0X: 1.0 hrs,   ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs -  │
│           ┆            ┆ OT3.9X: 7.0 h…     ┆       ┆               ┆              ┆ Authorized) │
│ 103092092 ┆ 2026-02-17 ┆ OT3.9X: 8.0 hrs    ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs -  │
│           ┆            ┆                    ┆       ┆               ┆              ┆ Authorized) │
│ 103170927 ┆ 2025-04-30 ┆ OT3.0X: 8.0 hrs    ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs -  │
│           ┆            ┆                    ┆       ┆               ┆              ┆ Authorized) │
│ 102477422 ┆ 2026-02-16 ┆ OT3.0X: 8.0 hrs    ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs -  │
│           ┆            ┆                    ┆       ┆               ┆              ┆ Authorized) │
│ 103082385 ┆ 2026-01-20 ┆ NSA: 8.0 hrs,      ┆ 4.0   ┆ Authorized    ┆ Authorized   ┆ (4.0 hrs -  │
│           ┆            ┆ OT1.5X: 4.0 hrs    ┆       ┆               ┆              ┆ Authorized) │
│ 103132424 ┆ 2026-05-06 ┆ OT1.5X: 2.5 hrs    ┆ 2.5   ┆               ┆ Authorized   ┆ (2.5 hrs -  │
│           ┆            ┆                    ┆       ┆               ┆              ┆ Authorized) │
│ 102477293 ┆ 2026-02-05 ┆ OT1.5X: 1.0 hrs    ┆ 1.0   ┆               ┆ Authorized   ┆ (1.0 hrs -  │
│           ┆            ┆                    ┆       ┆               ┆              ┆ Authorized) │
│ 102449700 ┆ 2025-04-30 ┆ OT3.0X: 1.0 hrs,   ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs -  │
│           ┆            ┆ OT3.9X: 7.0 h…     ┆       ┆               ┆              ┆ Authorized) │
│ 102482237 ┆ 2025-04-30 ┆ OT3.0X: 8.0 hrs    ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs -  │
│           ┆            ┆                    ┆       ┆               ┆              ┆ Authorized) │
│ 103060453 ┆ 2026-02-16 ┆ OT3.0X: 8.0 hrs    ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs -  │
│           ┆            ┆                    ┆       ┆               ┆              ┆ Authorized) │
│ 102855952 ┆ 2026-05-23 ┆ NSA: 7.0 hrs,      ┆ 2.0   ┆ Authorized    ┆ Authorized   ┆ (2.0 hrs -  │
│           ┆            ┆ OT1.5X: 2.0 hrs    ┆       ┆               ┆              ┆ Authorized) │
│ 103082112 ┆ 2026-01-20 ┆ OT1.5X: 2.0 hrs    ┆ 2.0   ┆               ┆ Authorized   ┆ (2.0 hrs -  │
│           ┆            ┆                    ┆       ┆               ┆              ┆ Authorized) │
│ 103109343 ┆ 2026-01-04 ┆ NSA: 8.0 hrs,      ┆ 3.0   ┆ Authorized    ┆ Authorized   ┆ (3.0 hrs -  │
│           ┆            ┆ OT1.5X: 3.0 hrs    ┆       ┆               ┆              ┆ Authorized) │
│ 102482237 ┆ 2026-02-04 ┆ OT2.7X: 3.0 hrs    ┆ 3.0   ┆               ┆ Authorized   ┆ (3.0 hrs -  │
│           ┆            ┆                    ┆       ┆               ┆              ┆ Authorized) │
│ 103125208 ┆ 2026-02-18 ┆ OT3.0X: 1.0 hrs,   ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs -  │
│           ┆            ┆ OT3.9X: 7.0 h…     ┆       ┆               ┆              ┆ Authorized) │
│ …         ┆ …          ┆ …                  ┆ …     ┆ …             ┆ …            ┆ …           │
│ 103121097 ┆ 2026-02-19 ┆ OT3.0X: 8.0 hrs    ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs -  │
│           ┆            ┆                    ┆       ┆               ┆              ┆ Authorized) │
│ 103105143 ┆ 2026-03-21 ┆ NSA: 7.5 hrs,      ┆ 2.5   ┆ Authorized    ┆ Authorized   ┆ (2.5 hrs -  │
│           ┆            ┆ OT2.1X: 2.5 hrs    ┆       ┆               ┆              ┆ Authorized) │
│ 102484482 ┆ 2026-03-24 ┆ NSA: 8.0 hrs,      ┆ 2.5   ┆ Authorized    ┆ Authorized   ┆ (2.5 hrs -  │
│           ┆            ┆ OT1.5X: 2.5 hrs    ┆       ┆               ┆              ┆ Authorized) │
│ 103111956 ┆ 2026-02-19 ┆ OT3.0X: 8.0 hrs    ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs -  │
│           ┆            ┆                    ┆       ┆               ┆              ┆ Authorized) │
│ 103129415 ┆ 2025-09-01 ┆ OT3.0X: 8.0 hrs    ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs -  │
│           ┆            ┆                    ┆       ┆               ┆              ┆ Authorized) │
│ 103173195 ┆ 2026-05-06 ┆ NSA: 7.0 hrs,      ┆ 2.0   ┆ Authorized    ┆ Authorized   ┆ (2.0 hrs -  │
│           ┆            ┆ OT1.5X: 2.0 hrs    ┆       ┆               ┆              ┆ Authorized) │
│ 102843519 ┆ 2026-04-26 ┆ OT3.0X: 8.0 hrs    ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs -  │
│           ┆            ┆                    ┆       ┆               ┆              ┆ Authorized) │
│ 102456993 ┆ 2026-01-12 ┆ OT2.0X: 4.0 hrs    ┆ 4.0   ┆               ┆ Authorized   ┆ (4.0 hrs -  │
│           ┆            ┆                    ┆       ┆               ┆              ┆ Authorized) │
│ 102456984 ┆ 2026-04-28 ┆ OT1.5X: 4.0 hrs    ┆ 4.0   ┆               ┆ Authorized   ┆ (4.0 hrs -  │
│           ┆            ┆                    ┆       ┆               ┆              ┆ Authorized) │
│ 103119654 ┆ 2025-09-02 ┆ OT3.0X: 1.0 hrs,   ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs -  │
│           ┆            ┆ OT3.9X: 7.0 h…     ┆       ┆               ┆              ┆ Authorized) │
│ 103109089 ┆ 2026-04-26 ┆ OT3.0X: 1.0 hrs,   ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs -  │
│           ┆            ┆ OT3.9X: 7.0 h…     ┆       ┆               ┆              ┆ Authorized) │
│ 103121098 ┆ 2026-01-22 ┆ NSA: 8.0 hrs,      ┆ 1.0   ┆ Authorized    ┆ Authorized   ┆ (1.0 hrs -  │
│           ┆            ┆ OT1.5X: 1.0 hrs    ┆       ┆               ┆              ┆ Authorized) │
│ 103082385 ┆ 2026-04-02 ┆ OT2.0X: 3.5 hrs    ┆ 3.5   ┆               ┆ Authorized   ┆ (3.5 hrs -  │
│           ┆            ┆                    ┆       ┆               ┆              ┆ Authorized) │
│ 103550261 ┆ 2026-06-10 ┆ OT2.0X: 4.0 hrs    ┆ 4.0   ┆               ┆ Authorized   ┆ (4.0 hrs -  │
│           ┆            ┆                    ┆       ┆               ┆              ┆ Authorized) │
│ 102211220 ┆ 2025-05-01 ┆ OT3.0X: 1.0 hrs,   ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs -  │
│           ┆            ┆ OT3.9X: 7.0 h…     ┆       ┆               ┆              ┆ Authorized) │
│ 102477293 ┆ 2026-01-17 ┆ OT1.5X: 1.0 hrs    ┆ 1.0   ┆               ┆ Authorized   ┆ (1.0 hrs -  │
│           ┆            ┆                    ┆       ┆               ┆              ┆ Authorized) │
│ 103082121 ┆ 2026-01-06 ┆ NSA: 1.0 hrs,      ┆ 1.5   ┆ Authorized    ┆ Authorized   ┆ (1.5 hrs -  │
│           ┆            ┆ OT1.5X: 1.5 hrs    ┆       ┆               ┆              ┆ Authorized) │
│ 103060453 ┆ 2026-02-04 ┆ NSA: 7.0 hrs,      ┆ 1.0   ┆ Authorized    ┆ Authorized   ┆ (1.0 hrs -  │
│           ┆            ┆ OT2.0X: 1.0 hrs    ┆       ┆               ┆              ┆ Authorized) │
│ 102029874 ┆ 2026-03-12 ┆ NSA: 8.0 hrs,      ┆ 4.0   ┆ Authorized    ┆ Authorized   ┆ (4.0 hrs -  │
│           ┆            ┆ OT1.5X: 4.0 hrs    ┆       ┆               ┆              ┆ Authorized) │
│ 103293766 ┆ 2026-05-01 ┆ OT3.9X: 8.0 hrs    ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs -  │
│           ┆            ┆                    ┆       ┆               ┆              ┆ Authorized) │
│ 103125208 ┆ 2026-03-24 ┆ NSA: 7.0 hrs,      ┆ 1.5   ┆ Authorized    ┆ Authorized   ┆ (1.5 hrs -  │
│           ┆            ┆ OT2.1X: 1.5 hrs    ┆       ┆               ┆              ┆ Authorized) │
│ 103109136 ┆ 2026-01-17 ┆ NSA: 8.0 hrs,      ┆ 1.5   ┆ Authorized    ┆ Authorized   ┆ (1.5 hrs -  │
│           ┆            ┆ OT1.5X: 1.5 hrs    ┆       ┆               ┆              ┆ Authorized) │
│ 103082385 ┆ 2026-03-07 ┆ OT1.5X: 4.0 hrs    ┆ 4.0   ┆               ┆ Authorized   ┆ (4.0 hrs -  │
│           ┆            ┆                    ┆       ┆               ┆              ┆ Authorized) │
│ 103124250 ┆ 2025-09-02 ┆ OT3.0X: 8.0 hrs    ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs -  │
│           ┆            ┆                    ┆       ┆               ┆              ┆ Authorized) │
│ 103171103 ┆ 2026-03-10 ┆ NSA: 8.0 hrs,      ┆ 4.0   ┆ Authorized    ┆ Authorized   ┆ (4.0 hrs -  │
│           ┆            ┆ OT1.5X: 4.0 hrs    ┆       ┆               ┆              ┆ Authorized) │
└───────────┴────────────┴────────────────────┴───────┴───────────────┴──────────────┴─────────────┘
shape: (5, 4)
┌────────┬───────────┬──────────────────────────┬────────────────────┐
│ Month  ┆ EID       ┆ employee_name            ┆ count_working_days │
│ ---    ┆ ---       ┆ ---                      ┆ ---                │
│ str    ┆ i64       ┆ str                      ┆ i32                │
╞════════╪═══════════╪══════════════════════════╪════════════════════╡
│ Apr-25 ┆ 101993774 ┆ HIEU THI TRAN            ┆ 22                 │
│ Apr-25 ┆ 102029874 ┆ THIEN THANH TOAN  TRUONG ┆ 20                 │
│ Apr-25 ┆ 102173363 ┆ THI NGOC BICH  TRAN      ┆ 23                 │
│ Apr-25 ┆ 102173384 ┆ HUU VINH  MAI            ┆ 22                 │
│ Apr-25 ┆ 102211178 ┆ THI QUYNH TRANG  NGUYEN  ┆ 22                 │
└────────┴───────────┴──────────────────────────┴────────────────────┘
['After Call Work', 'Available', 'Available Cases', 'Available Chat', 'Available Phone', 'Break', 'Coaching', 'End of Shift', 'HR Accom / Prayer', 'Login', 'Lunch', 'Not Ready', 'Outbound Call', 'Personal', 'Restroom', 'System Issue', 'Team Meeting', 'Training', 'Unavailable']
shape: (61, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ Date_Conve ┆ Staff Hour ┆ Total      ┆ THT(In    ┆ Avail     ┆ Other Pro ┆ Non Produ ┆ Present   │
│ rted       ┆ (In Hours) ┆ Break (In  ┆ Hours)    ┆ Time(In   ┆ ductive   ┆ ctive Aux ┆ for Calcu │
│ ---        ┆ ---        ┆ Hours)     ┆ ---       ┆ Hours)    ┆ Aux(In    ┆ (In       ┆ lation    │
│ date       ┆ f64        ┆ ---        ┆ f64       ┆ ---       ┆ Hours)    ┆ Hours)    ┆ ---       │
│            ┆            ┆ f64        ┆           ┆ f64       ┆ ---       ┆ ---       ┆ u32       │
│            ┆            ┆            ┆           ┆           ┆ f64       ┆ f64       ┆           │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2026-05-03 ┆ 56.637813  ┆ 10.918191  ┆ 27.779953 ┆ 16.67326  ┆ 0.41182   ┆ 0.854589  ┆ 16        │
│ 2026-05-04 ┆ 414.054502 ┆ 54.217021  ┆ 243.25518 ┆ 94.836161 ┆ 14.121649 ┆ 7.624491  ┆ 52        │
│            ┆            ┆            ┆ 1         ┆           ┆           ┆           ┆           │
│ 2026-05-05 ┆ 454.498917 ┆ 67.110563  ┆ 198.98613 ┆ 167.22553 ┆ 10.468144 ┆ 10.70854  ┆ 53        │
│            ┆            ┆            ┆ 8         ┆ 1         ┆           ┆           ┆           │
│ 2026-05-06 ┆ 436.650643 ┆ 63.463804  ┆ 186.95855 ┆ 150.29796 ┆ 21.37914  ┆ 14.551183 ┆ 50        │
│            ┆            ┆            ┆           ┆ 7         ┆           ┆           ┆           │
│ 2026-05-07 ┆ 439.421022 ┆ 58.676418  ┆ 266.96236 ┆ 86.330405 ┆ 18.420387 ┆ 9.031449  ┆ 50        │
│            ┆            ┆            ┆ 2         ┆           ┆           ┆           ┆           │
│ 2026-05-08 ┆ 445.087884 ┆ 59.646116  ┆ 260.73814 ┆ 100.03439 ┆ 9.38446   ┆ 15.284769 ┆ 52        │
│            ┆            ┆            ┆ 2         ┆ 6         ┆           ┆           ┆           │
│ 2026-05-09 ┆ 381.413317 ┆ 56.436324  ┆ 222.33316 ┆ 93.009978 ┆ 3.597835  ┆ 6.036011  ┆ 42        │
│            ┆            ┆            ┆ 9         ┆           ┆           ┆           ┆           │
│ 2026-05-10 ┆ 331.26836  ┆ 37.625137  ┆ 181.38107 ┆ 103.96101 ┆ 0.520187  ┆ 7.780944  ┆ 37        │
│            ┆            ┆            ┆ 7         ┆ 4         ┆           ┆           ┆           │
│ 2026-05-11 ┆ 384.489424 ┆ 56.064071  ┆ 221.75921 ┆ 96.154832 ┆ 6.049974  ┆ 4.461332  ┆ 44        │
│            ┆            ┆            ┆ 5         ┆           ┆           ┆           ┆           │
│ 2026-05-12 ┆ 377.018772 ┆ 57.833674  ┆ 174.40594 ┆ 135.37437 ┆ 6.542399  ┆ 2.862383  ┆ 46        │
│            ┆            ┆            ┆ 6         ┆ 1         ┆           ┆           ┆           │
│ 2026-05-13 ┆ 362.95395  ┆ 53.325501  ┆ 167.49180 ┆ 129.48364 ┆ 4.555942  ┆ 8.097054  ┆ 43        │
│            ┆            ┆            ┆ 6         ┆ 6         ┆           ┆           ┆           │
│ 2026-05-14 ┆ 243.548395 ┆ 36.570119  ┆ 160.82266 ┆ 38.328254 ┆ 5.004319  ┆ 2.823036  ┆ 30        │
│            ┆            ┆            ┆ 6         ┆           ┆           ┆           ┆           │
│ 2026-05-15 ┆ 372.406094 ┆ 53.177927  ┆ 234.90115 ┆ 58.926345 ┆ 20.824983 ┆ 4.575681  ┆ 45        │
│            ┆            ┆            ┆ 8         ┆           ┆           ┆           ┆           │
│ 2026-05-16 ┆ 437.843854 ┆ 61.910678  ┆ 236.73761 ┆ 124.37217 ┆ 10.493311 ┆ 4.330077  ┆ 50        │
│            ┆            ┆            ┆ 1         ┆ 7         ┆           ┆           ┆           │
│ 2026-05-17 ┆ 421.648458 ┆ 61.638151  ┆ 226.46443 ┆ 109.48377 ┆ 19.195787 ┆ 4.866302  ┆ 47        │
│            ┆            ┆            ┆ 8         ┆ 9         ┆           ┆           ┆           │
│ 2026-05-18 ┆ 457.332717 ┆ 65.022969  ┆ 238.34538 ┆ 141.35810 ┆ 8.453966  ┆ 4.152298  ┆ 52        │
│            ┆            ┆            ┆ 1         ┆ 2         ┆           ┆           ┆           │
│ 2026-05-19 ┆ 443.292769 ┆ 64.947054  ┆ 282.96770 ┆ 85.691193 ┆ 4.484816  ┆ 5.202004  ┆ 52        │
│            ┆            ┆            ┆ 2         ┆           ┆           ┆           ┆           │
│ 2026-05-20 ┆ 468.439224 ┆ 63.384255  ┆ 285.06903 ┆ 101.50701 ┆ 12.303706 ┆ 6.175213  ┆ 55        │
│            ┆            ┆            ┆ 4         ┆ 6         ┆           ┆           ┆           │
│ 2026-05-21 ┆ 477.98435  ┆ 61.964841  ┆ 284.95753 ┆ 110.02058 ┆ 15.304662 ┆ 5.736729  ┆ 57        │
│            ┆            ┆            ┆ 8         ┆           ┆           ┆           ┆           │
│ 2026-05-22 ┆ 530.469718 ┆ 71.115847  ┆ 293.25328 ┆ 144.95081 ┆ 9.257011  ┆ 11.892766 ┆ 63        │
│            ┆            ┆            ┆ 1         ┆ 3         ┆           ┆           ┆           │
│ 2026-05-23 ┆ 464.359803 ┆ 64.134651  ┆ 259.77577 ┆ 124.77357 ┆ 9.230216  ┆ 6.445589  ┆ 52        │
│            ┆            ┆            ┆ 1         ┆ 6         ┆           ┆           ┆           │
│ 2026-05-24 ┆ 429.599833 ┆ 60.450493  ┆ 260.82477 ┆ 97.548332 ┆ 7.015295  ┆ 3.760937  ┆ 49        │
│            ┆            ┆            ┆ 6         ┆           ┆           ┆           ┆           │
│ 2026-05-25 ┆ 449.917033 ┆ 65.200237  ┆ 264.15838 ┆ 104.46182 ┆ 12.339507 ┆ 3.75708   ┆ 51        │
│            ┆            ┆            ┆ 1         ┆ 9         ┆           ┆           ┆           │
│ 2026-05-26 ┆ 425.271394 ┆ 64.096161  ┆ 228.01741 ┆ 116.33465 ┆ 12.601051 ┆ 4.222107  ┆ 51        │
│            ┆            ┆            ┆ 8         ┆ 6         ┆           ┆           ┆           │
│ 2026-05-27 ┆ 421.795274 ┆ 59.700685  ┆ 230.63311 ┆ 112.87409 ┆ 5.595606  ┆ 12.991766 ┆ 52        │
│            ┆            ┆            ┆ 8         ┆ 9         ┆           ┆           ┆           │
│ …          ┆ …          ┆ …          ┆ …         ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2026-06-08 ┆ 527.942182 ┆ 79.457658  ┆ 344.12046 ┆ 90.912685 ┆ 11.279435 ┆ 2.171935  ┆ 59        │
│            ┆            ┆            ┆ 8         ┆           ┆           ┆           ┆           │
│ 2026-06-09 ┆ 461.587098 ┆ 61.043064  ┆ 306.62870 ┆ 87.875407 ┆ 1.617554  ┆ 4.422366  ┆ 52        │
│            ┆            ┆            ┆ 7         ┆           ┆           ┆           ┆           │
│ 2026-06-10 ┆ 436.067228 ┆ 67.172036  ┆ 297.65796 ┆ 62.568529 ┆ 4.642065  ┆ 4.026632  ┆ 54        │
│            ┆            ┆            ┆ 7         ┆           ┆           ┆           ┆           │
│ 2026-06-11 ┆ 554.395743 ┆ 84.059884  ┆ 383.43954 ┆ 72.435491 ┆ 9.764885  ┆ 4.695937  ┆ 62        │
│            ┆            ┆            ┆ 6         ┆           ┆           ┆           ┆           │
│ 2026-06-12 ┆ 511.216596 ┆ 76.539585  ┆ 389.13749 ┆ 41.759822 ┆ 0.33503   ┆ 3.444665  ┆ 62        │
│            ┆            ┆            ┆ 3         ┆           ┆           ┆           ┆           │
│ 2026-06-13 ┆ 556.002363 ┆ 80.510383  ┆ 422.84165 ┆ 39.201571 ┆ 9.535864  ┆ 3.912888  ┆ 66        │
│            ┆            ┆            ┆ 7         ┆           ┆           ┆           ┆           │
│ 2026-06-14 ┆ 594.341039 ┆ 88.098609  ┆ 415.53975 ┆ 69.302734 ┆ 17.223451 ┆ 4.176009  ┆ 70        │
│            ┆            ┆            ┆ 1         ┆           ┆           ┆           ┆           │
│ 2026-06-15 ┆ 692.502995 ┆ 104.030874 ┆ 490.40167 ┆ 81.582939 ┆ 11.342527 ┆ 5.14498   ┆ 81        │
│            ┆            ┆            ┆ 5         ┆           ┆           ┆           ┆           │
│ 2026-06-16 ┆ 559.90295  ┆ 86.833178  ┆ 390.65757 ┆ 68.220816 ┆ 9.254957  ┆ 4.93642   ┆ 64        │
│            ┆            ┆            ┆ 9         ┆           ┆           ┆           ┆           │
│ 2026-06-17 ┆ 560.216126 ┆ 85.997188  ┆ 339.73054 ┆ 108.39782 ┆ 22.680115 ┆ 3.410457  ┆ 68        │
│            ┆            ┆            ┆ 3         ┆ 2         ┆           ┆           ┆           │
│ 2026-06-18 ┆ 583.635396 ┆ 88.570134  ┆ 355.29786 ┆ 112.91483 ┆ 21.106504 ┆ 5.744555  ┆ 67        │
│            ┆            ┆            ┆ 3         ┆ 2         ┆           ┆           ┆           │

In [55]:
def input_data(folder_path, sheet_name=None):
    file_paths = glob.glob(f"{folder_path}/*.xlsx") + glob.glob(f"{folder_path}/*.csv")
    df_list = []

    for file in file_paths:
        if file.endswith('.xlsx'):
            df = pl.read_excel(file, sheet_name=sheet_name, infer_schema_length=0)
        elif file.endswith('.csv'):
            try:
                df = pl.read_csv(file, encoding="utf-8", infer_schema_length=0)
            except:
                df = pl.read_csv(file, encoding="ISO-8859-1", ignore_errors=True, infer_schema_length=0)
        
        df = df.with_columns([
            pl.col(col).cast(pl.String) 
            for col in df.columns
        ])
        
        df_list.append(df)
    
    merged_df = pl.concat(df_list, how='vertical')

    return merged_df

In [56]:
pl.Config.set_tbl_rows(50)
pl.Config.set_tbl_cols(100)

def filter_shift_discrepancies(df_input) -> pl.DataFrame:
    if isinstance(df_input, pd.DataFrame):
        df = pl.from_pandas(df_input)
    else:
        df = df_input

    # Requirement 1: hc_actual != hc_present
    hc_mismatch_condition = (
        pl.col("hc_actual").cast(pl.Float64, strict=False).fill_null(0.0) != 
        pl.col("hc_present").cast(pl.Float64, strict=False).fill_null(0.0)
    )

    # Requirement 2: Target > 3.75 AND sum_productive <= 3
    productivity_condition = (
        (pl.col("Target").cast(pl.Float64, strict=False).fill_null(0.0) > 3.75) &
        (pl.col("sum_productive").cast(pl.Float64, strict=False).fill_null(0.0) <= 3.0)
    )

    # Exclude any LOB containing "Support" (e.g. "Support", "Support - Ops", etc.)
    lob_condition = (~pl.col("LOB").str.contains("Support", literal=True) & ~pl.col("LOB").str.contains("Training", literal=True))

    # Exclude Training/Offline shifts, Off Phone Misc, and PO from Shift Tracking
    shift_condition = (
        (~pl.col("First Shift").is_in(["Training", "Offline", "Off"])) &
        (~pl.col("Shift Tracking").is_in(["Training Offline", "Off Phone Misc", "PO"])) &
        (
            pl.col("Shift Tracking").is_in(["PR", "PR - OT"]) |
            (pl.col("sum_productive").cast(pl.Float64, strict=False).fill_null(0.0) > 0.0)
        )
    )
 

    # Main filtering logic
    result = df.filter(
        (hc_mismatch_condition | productivity_condition) &
        lob_condition &
        shift_condition
    )

    if "Date_Converted" in result.columns:
        result = result.sort("Date_Converted")

    return result

RTA_REPORT_GENERATE = input_data(f'{first_glob}/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/STORAGE_OUTPUT_RTA')
print(RTA_REPORT_GENERATE.columns)

RTA_REPORT_GENERATE = RTA_REPORT_GENERATE.with_columns([
    pl.col('Date_Converted').str.slice(0, 10).str.strptime(pl.Date, format='%Y-%m-%d'),
    pl.col('Target').cast(pl.Float64), 
    pl.col('duration').cast(pl.Float64),
    pl.col('sum_productive').cast(pl.Float64),
    pl.col('start').str.strip_chars().str.to_datetime("%Y-%m-%d %H:%M:%S%.3f", strict=False),
    pl.col('end').str.strip_chars().str.to_datetime("%Y-%m-%d %H:%M:%S%.3f", strict=False)
])

RTA_REPORT_GENERATE = RTA_REPORT_GENERATE.filter(
    pl.col('duration').is_not_null() | (pl.col('Target') > 0)
)

RTA_REPORT_GENERATE = RTA_REPORT_GENERATE.with_columns([
    pl.col('Shift Tracking').cast(pl.Utf8).str.strip_chars(),
    pl.col('Open Time').cast(pl.Float64).fill_null(0.0), 
    pl.col('Extra Time').cast(pl.Float64).fill_null(0.0)    
])
 
RTA_REPORT_GENERATE = RTA_REPORT_GENERATE.with_columns([
    pl.when(pl.col('Shift Tracking') == 'HDL').then(0.5)
    .when(
        (pl.col('Shift Tracking').is_in(['PR','PR - OT','PO'])) & 
        ((pl.col('Open Time') > 0) | (pl.col('Extra Time') > 0))
    ).then(1.0)
    .when(
        (pl.col('Shift Tracking').is_in([
            'Training Offline', 'Sick Leave', 'Paid Leave', 'Billable Training'
        ])) & (pl.col('Open Time') == 0)
    ).then(1.0)
    .when(
        (pl.col('Shift Tracking') != 'HDL') & 
        (pl.col('Shift Tracking') != 'PR') & 
        (pl.col('Open Time') == 0)
    ).then(0.0)
    .otherwise(None)
    .alias('hc_present')
])
 
filtered_data = RTA_REPORT_GENERATE.select([
    'Date_Converted', 'Employee Name', 'LOB', 'Detail Status','IEX ID','First Shift','Shift Tracking', 
    'start', 'end','Target', 'duration', 'sum_productive','training-idle','Extra Time', 'hc_schedule',
    'hc_actual', 'hc_present'
])
filtered_data = filtered_data.with_columns([
    pl.col('hc_actual').cast(pl.Float64),
    pl.col('hc_present').cast(pl.Float64)
])
 
start_date = '2026-06-01'
end_date = '2026-07-01'
 
start_date_parsed = pl.lit(start_date).str.strptime(pl.Date, format='%Y-%m-%d')
end_date_parsed = pl.lit(end_date).str.strptime(pl.Date, format='%Y-%m-%d')
 
sorted_data = filtered_data.sort('Date_Converted')
filtered_data = sorted_data.filter((pl.col('Date_Converted') >= start_date_parsed) & (pl.col('Date_Converted') <= end_date_parsed))
 
filtered_data_pd = filtered_data.to_pandas()

filtered_data_1 = filter_shift_discrepancies(filtered_data)
filtered_data_1

['Year', 'Month', 'Week_Monday', 'Date_Converted', 'Employee Name', 'Email Id', 'OracleID', 'IEX ID', 'Target', 'Datetime_Fluctuate_Start_Shift', 'Datetime_Fluctuate_End_Shift', 'Fluctuate Shift', 'Datetime_First_Start_Shift', 'Datetime_First_End_Shift', 'First Shift', 'Alias', 'LOB', 'LOB_2', 'LOB_3', 'Supervisor Name', 'Wave', 'Detail Status', 'Status', 'Time_Of_Day', 'Open Time', 'Extra Time', 'Break Time', 'Lunch Time', 'Training', 'NCNS', 'AL', 'Unplanned', 'Planned', 'Roster Presented', 'Roster Scheduled', 'Night_Shift', 'Shift Tracking', 'OT Type', 'Combined OT Range', 'OT PreShift', 'OT PostShift', 'start', 'end', 'total_time_chat_handle', 'sum_productive', 'break', 'lunch', 'coaching-idle', 'training-idle', 'outbound-idle', 'break_count', 'other_status', 'over_break', 'over_lunch', 'exceed_break', 'duration', 'hc_actual', 'hc_schedule', 'time_late', 'time_leave', 'lateness', 'adherence_time', 'ramco_marked', 'nsa_authorize', 'ot_authorize', 'hours', 'ot_status', 'ot_type', 'days_count', 'nm_group', 'nsa_group', 'ot_group']

shape: (9, 17)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ Dat ┆ Emp ┆ LOB ┆ Det ┆ IEX ┆ Fir ┆ Shi ┆ sta ┆ end ┆ Tar ┆ dur ┆ sum ┆ tra ┆ Ext ┆ hc_ ┆ hc_ ┆ hc_ │
│ e_C ┆ loy ┆ --- ┆ ail ┆ ID  ┆ st  ┆ ft  ┆ rt  ┆ --- ┆ get ┆ ati ┆ _pr ┆ ini ┆ ra  ┆ sch ┆ act ┆ pre │
│ onv ┆ ee  ┆ str ┆ Sta ┆ --- ┆ Shi ┆ Tra ┆ --- ┆ dat ┆ --- ┆ on  ┆ odu ┆ ng- ┆ Tim ┆ edu ┆ ual ┆ sen │
│ ert ┆ Nam ┆     ┆ tus ┆ str ┆ ft  ┆ cki ┆ dat ┆ eti ┆ f64 ┆ --- ┆ cti ┆ idl ┆ e   ┆ le  ┆ --- ┆ t   │
│ ed  ┆ e   ┆     ┆ --- ┆     ┆ --- ┆ ng  ┆ eti ┆ me[ ┆     ┆ f64 ┆ ve  ┆ e   ┆ --- ┆ --- ┆ f64 ┆ --- │
│ --- ┆ --- ┆     ┆ str ┆     ┆ str ┆ --- ┆ me[ ┆ ms] ┆     ┆     ┆ --- ┆ --- ┆ f64 ┆ str ┆     ┆ f64 │
│ dat ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ ms] ┆     ┆     ┆     ┆ f64 ┆ str ┆     ┆     ┆     ┆     │
│ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 202 ┆ TRA ┆ Lod ┆ Lod ┆ 308 ┆ 200 ┆ PR  ┆ 202 ┆ 202 ┆ 3.7 ┆ 5.8 ┆ 4.5 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 0.5 ┆ 1.0 │
│ 6-0 ┆ N   ┆ gin ┆ gin ┆ 785 ┆ 0-0 ┆     ┆ 6-0 ┆ 6-0 ┆ 5   ┆ 821 ┆ 615 ┆     ┆     ┆     ┆     ┆     │
│ 6-0 ┆ THI ┆ g   ┆ g   ┆ 9   ┆ 500 ┆     ┆ 6-0 ┆ 6-0 ┆     ┆ 23  ┆ 48  ┆     ┆     ┆     ┆     ┆     │
│ 4   ┆ TUO ┆     ┆ Pro ┆     ┆     ┆     ┆ 4   ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ NG  ┆     ┆ duc ┆     ┆     ┆     ┆ 23: ┆ 05: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ VY  ┆     ┆ tio ┆     ┆     ┆     ┆ 25: ┆ 20: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆ 27  ┆ 50  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ NGU ┆ Lod ┆ Lod ┆ 310 ┆ 200 ┆ PR  ┆ 202 ┆ 202 ┆ 7.5 ┆ 5.8 ┆ 4.6 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 0.5 ┆ 1.0 │
│ 6-0 ┆ YEN ┆ gin ┆ gin ┆ 933 ┆ 0-0 ┆     ┆ 6-0 ┆ 6-0 ┆     ┆ 897 ┆ 237 ┆     ┆     ┆     ┆     ┆     │
│ 6-0 ┆ DIN ┆ g   ┆ g   ┆ 8   ┆ 500 ┆     ┆ 6-0 ┆ 6-0 ┆     ┆ 12  ┆ 99  ┆     ┆     ┆     ┆     ┆     │
│ 4   ┆ H   ┆     ┆ Pro ┆     ┆     ┆     ┆ 4   ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ TUA ┆     ┆ duc ┆     ┆     ┆     ┆ 23: ┆ 04: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ N   ┆     ┆ tio ┆     ┆     ┆     ┆ 03: ┆ 57: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆ 46  ┆ 09  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ PHU ┆ Lod ┆ Lod ┆ 308 ┆ 200 ┆ PR  ┆ 202 ┆ 202 ┆ 3.7 ┆ 5.2 ┆ 4.0 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 0.5 ┆ 1.0 │
│ 6-0 ┆ NG  ┆ gin ┆ gin ┆ 533 ┆ 0-0 ┆     ┆ 6-0 ┆ 6-0 ┆ 5   ┆ 434 ┆ 103 ┆     ┆     ┆     ┆     ┆     │
│ 6-0 ┆ NGO ┆ g   ┆ g   ┆ 8   ┆ 500 ┆     ┆ 6-0 ┆ 6-0 ┆     ┆ 75  ┆ 44  ┆     ┆     ┆     ┆     ┆     │
│ 4   ┆ C   ┆     ┆ Pro ┆     ┆     ┆     ┆ 4   ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ TRA ┆     ┆ duc ┆     ┆     ┆     ┆ 23: ┆ 05: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ M   ┆     ┆ tio ┆     ┆     ┆     ┆ 52: ┆ 07: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆ 50  ┆ 26  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ TRA ┆ Lod ┆ Lod ┆ 309 ┆ 060 ┆ PR  ┆ 202 ┆ 202 ┆ 7.5 ┆ 6.2 ┆ 5.6 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 0.5 ┆ 1.0 │
│ 6-0 ┆ N   ┆ gin ┆ gin ┆ 679 ┆ 0-1 ┆     ┆ 6-0 ┆ 6-0 ┆     ┆ 224 ┆ 656 ┆     ┆     ┆     ┆     ┆     │
│ 6-0 ┆ THI ┆ g   ┆ g   ┆ 8   ┆ 500 ┆     ┆ 6-0 ┆ 6-0 ┆     ┆ 65  ┆ 16  ┆     ┆     ┆     ┆     ┆     │
│ 5   ┆ BIC ┆     ┆ Pro ┆     ┆     ┆     ┆ 5   ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ H   ┆     ┆ duc ┆     ┆     ┆     ┆ 06: ┆ 15: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ LOI ┆     ┆ tio ┆     ┆     ┆     ┆ 00: ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆ 15  ┆ 15  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ HOA ┆ Lod ┆ -   ┆ 303 ┆ 060 ┆ PR  ┆ 202 ┆ 202 ┆ 5.5 ┆ 6.7 ┆ 5.4 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 0.5 ┆ 1.0 │
│ 6-0 ┆ NG  ┆ gin ┆     ┆ 667 ┆ 0-1 ┆     ┆ 6-0 ┆ 6-0 ┆     ┆ 837 ┆ 808 ┆     ┆     ┆     ┆     ┆     │
│ 6-1 ┆ XUA ┆ g_N ┆     ┆ 5   ┆ 500 ┆     ┆ 6-1 ┆ 6-1 ┆     ┆ 27  ┆ 03  ┆     ┆     ┆     ┆     ┆     │
│ 0   ┆ N   ┆ est ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ NHI ┆ ing ┆     ┆     ┆     ┆     ┆ 06: ┆ 12: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 09: ┆ 56: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 26  ┆ 27  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ HUY ┆ Lod ┆ Lod ┆ 308 ┆ 080 ┆ PR  ┆ 202 ┆ 202 ┆ 8.2 ┆ 5.6 ┆ 5.2 ┆ 0.4 ┆ 1.5 ┆ 1.0 ┆ 0.5 ┆ 1.0 │
│ 6-0 ┆ NH  ┆ gin ┆ gin ┆ 475 ┆ 0-1 ┆ -   ┆ 6-0 ┆ 6-0 ┆ 5   ┆ 259 ┆ 202 ┆ 047 ┆     ┆     ┆     ┆     │
│ 6-1 ┆ NGO ┆ g   ┆ g   ┆ 6   ┆ 700 ┆ OT  ┆ 6-1 ┆ 6-1 ┆     ┆ 55  ┆ 6   ┆ 422 ┆     ┆     ┆     ┆     │
│ 8   ┆ C   ┆     ┆ Pro ┆     ┆     ┆     ┆ 8   ┆ 8   ┆     ┆     ┆     ┆ 306 ┆     ┆     ┆     ┆     │
│     ┆ HUE ┆     ┆ duc ┆     ┆     ┆     ┆ 06: ┆ 12: ┆     ┆     ┆     ┆ 405 ┆     ┆     ┆     ┆     │
│     ┆ TRA ┆     ┆ tio ┆     ┆     ┆     ┆ 30: ┆ 08: ┆     ┆     ┆     ┆ 173 ┆     ┆     ┆     ┆     │
│     ┆ NG  ┆     ┆ n   ┆     ┆     ┆     ┆ 30  ┆ 03  ┆     ┆     ┆     ┆ 4   ┆     ┆     ┆     ┆     │
│ 202 ┆ TRI ┆ Non ┆ Non ┆ 300 ┆ 200 ┆ PR  ┆ nul ┆ nul ┆ 7.5 ┆ nul ┆ nul ┆ nul ┆ 0.0 ┆ nul ┆ nul ┆ 1.0 │
│ 6-0 ┆ NH  ┆ _Lo ┆ Lod ┆ 557 ┆ 0-0 ┆     ┆ l   ┆ l   ┆     ┆ l   ┆ l   ┆ l   ┆     ┆ l   ┆ l   ┆     │
│ 6-2 ┆ HOA ┆ dgi ┆ gin ┆ 8   ┆ 500 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 0   ┆ NG  ┆ ng  ┆ g   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ NAM ┆     ┆ Pro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ duc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ tio ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ BUI ┆ Lod ┆ Lod ┆ 305 ┆ 050 ┆ PR  ┆ 202 ┆ 202 ┆ 7.5 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 0.0 ┆ 1.0 │
│ 6-0 ┆ BA  ┆ gin ┆ gin ┆ 230 ┆ 0-1 ┆     ┆ 6-0 ┆ 6-0 ┆     ┆ 252 ┆     ┆     ┆     ┆     ┆     ┆     │
│ 6-2 ┆ DUO ┆ g   ┆ g   ┆ 6   ┆ 400 ┆     ┆ 6-2 ┆ 6-2 ┆     ┆ 26  ┆     ┆     ┆     ┆     ┆     ┆     │
│ 4   ┆ NG  ┆     ┆ Pro ┆     ┆     ┆     ┆ 5   ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ duc ┆     ┆     ┆     ┆ 04: ┆ 05: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ tio ┆     ┆     ┆     ┆ 58: ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆ 47  ┆ 18  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ NGU ┆ Lod ┆ Lod ┆ 311 ┆ 210 ┆ PR  ┆ nul ┆ nul ┆ 7.5 ┆ nul ┆ nul ┆ nul ┆ 0.0 ┆ nul ┆ nul ┆ 1.0 │
│ 6-0 ┆ YEN ┆ gin ┆ gin ┆ 017 ┆ 0-0 ┆     ┆ l   ┆ l   ┆     ┆ l   ┆ l   ┆ l   ┆     ┆ l   ┆ l   ┆     │
│ 6-2 ┆ NGO ┆ g   ┆ g   ┆ 1   ┆ 600 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 6   ┆ C   ┆     ┆ Pro ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ HOA ┆     ┆ duc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ NG  ┆     ┆ tio ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ YEN ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [57]:
# ── FILTER IEX_BASE BY filtered_data_1 ───────────────────────────────────────

IEX_BASE_filtered = IEX_BASE.with_columns(
    pl.col("Agent").str.extract(r"Agent:\s*(\d+)", 1).alias("IEX_ID"),
    pl.col("Date").cast(pl.Utf8)
)
filter_keys = (
    filtered_data_1
    .select([
        pl.col("IEX ID").cast(pl.Utf8).alias("IEX_ID"),
        pl.col("Date_Converted").cast(pl.Utf8).alias("Date")
    ])
    .unique()
)
IEX_BASE_filtered = IEX_BASE_filtered.join(filter_keys, on=["IEX_ID", "Date"], how="semi")
IEX_BASE_filtered = IEX_BASE_filtered.with_columns(
    pl.col("Date").str.strptime(pl.Date, format="%Y-%m-%d", strict=False),
    pl.col("Generate Date").str.strptime(pl.Datetime, format="%m/%d/%y %I:%M %p", strict=False),
    pl.col("Start_Shift").str.strptime(pl.Time, format="%I:%M %p", strict=False),
    pl.col("End_Shift").str.strptime(pl.Time, format="%I:%M %p", strict=False),
    pl.lit(None).cast(pl.Utf8).alias("Scheduled Activity"),
    pl.lit(None).cast(pl.Utf8).alias("Start_Action"),
    pl.lit(None).cast(pl.Utf8).alias("End_Action"),
    pl.col("sheet_name").str.strip_chars('"').str.replace(r"IEX_Base_", "").alias("sheet_name")
).drop("IEX_ID").unique().sort("Date")

with pl.Config(tbl_rows=50, tbl_cols=20, fmt_str_lengths=100, tbl_width_chars=500):
    display(IEX_BASE_filtered)

shape: (9, 10)
┌─────────────────────────────────────┬────────────┬─────────────┬───────────┬────────────────────┬──────────────┬────────────┬────────────┬─────────────────────┬─────────────────────┐
│ Agent                               ┆ Date       ┆ Start_Shift ┆ End_Shift ┆ Scheduled Activity ┆ Start_Action ┆ End_Action ┆ sheet_name ┆ Export time         ┆ Generate Date       │
│ ---                                 ┆ ---        ┆ ---         ┆ ---       ┆ ---                ┆ ---          ┆ ---        ┆ ---        ┆ ---                 ┆ ---                 │
│ str                                 ┆ date       ┆ time        ┆ time      ┆ str                ┆ str          ┆ str        ┆ str        ┆ datetime[μs]        ┆ datetime[μs]        │
╞═════════════════════════════════════╪════════════╪═════════════╪═══════════╪════════════════════╪══════════════╪════════════╪════════════╪═════════════════════╪═════════════════════╡
│ Agent: 3087859 TRAN, THITUONGVY     ┆ 2026-06-04 ┆ 20:00:00    ┆ 05:00:00  ┆ null               ┆ null         ┆ null       ┆ 2026_06_01 ┆ 2026-07-02 11:45:51 ┆ 2026-06-10 04:32:00 │
│ Agent: 3085338 Phung, NgocTram      ┆ 2026-06-04 ┆ 20:00:00    ┆ 05:00:00  ┆ null               ┆ null         ┆ null       ┆ 2026_06_01 ┆ 2026-07-02 11:45:51 ┆ 2026-06-10 04:32:00 │
│ Agent: 3109338 Nguyen, DinhTuan     ┆ 2026-06-04 ┆ 20:00:00    ┆ 05:00:00  ┆ null               ┆ null         ┆ null       ┆ 2026_06_01 ┆ 2026-07-02 11:45:51 ┆ 2026-06-10 04:32:00 │
│ Agent: 3096798 Tran, ThiBichLoi     ┆ 2026-06-05 ┆ 06:00:00    ┆ 15:00:00  ┆ null               ┆ null         ┆ null       ┆ 2026_06_01 ┆ 2026-07-02 11:45:51 ┆ 2026-06-10 04:32:00 │
│ Agent: 3036675 Hoang, XuanNhi       ┆ 2026-06-10 ┆ 06:00:00    ┆ 15:00:00  ┆ null               ┆ null         ┆ null       ┆ 2026_06_08 ┆ 2026-07-02 11:45:51 ┆ 2026-06-17 06:16:00 │
│ Agent: 3084756 HUYNH, NGOCHUETRANG  ┆ 2026-06-18 ┆ 06:30:00    ┆ 17:30:00  ┆ null               ┆ null         ┆ null       ┆ 2026_06_15 ┆ 2026-07-02 11:45:51 ┆ 2026-06-23 04:04:00 │
│ Agent: 3005578 TRINH, HOANGNAM      ┆ 2026-06-20 ┆ 20:00:00    ┆ 05:00:00  ┆ null               ┆ null         ┆ null       ┆ 2026_06_15 ┆ 2026-07-02 11:45:51 ┆ 2026-06-23 04:04:00 │
│ Agent: 3052306 BUI, BADUONG         ┆ 2026-06-24 ┆ 05:00:00    ┆ 14:00:00  ┆ null               ┆ null         ┆ null       ┆ 2026_06_22 ┆ 2026-07-02 11:45:51 ┆ 2026-06-29 05:48:00 │
│ Agent: 3110171 Nguyen, NgocHoangYen ┆ 2026-06-26 ┆ 21:00:00    ┆ 06:00:00  ┆ null               ┆ null         ┆ null       ┆ 2026_06_22 ┆ 2026-07-02 11:45:51 ┆ 2026-06-29 05:48:00 │
└─────────────────────────────────────┴────────────┴─────────────┴───────────┴────────────────────┴──────────────┴────────────┴────────────┴─────────────────────┴─────────────────────┘

In [58]:
# def get_xlsx_filenames(data_dir):
#     xlsx_files = []
#     for filename in pathlib.Path(data_dir).glob('**/*.xlsx'):
#         xlsx_files.append(filename.name)
#     return xlsx_files
# def create_dataframe_with_filenames(data_dir):
#     xlsx_filenames = get_xlsx_filenames(data_dir)
#     df = pd.DataFrame(xlsx_filenames, columns=['Filename'])
#     return df
# def get_latest_xlsx_files(df):
#     df = df[df['Filename'].str.match(r'\d{4}-\d{2}-\d{2}\.xlsx')]
#     df['Date'] = pd.to_datetime(df['Filename'].str.replace('.xlsx', ''), format='%Y-%m-%d')
#     df_sorted = df.sort_values(by='Date', ascending=False)
#     latest_files = df_sorted.head(8)['Filename'].tolist()
#     return latest_files
# def delete_all_xlsx_files(directory):
#     for filename in pathlib.Path(directory).glob('*.xlsx'):
#         os.remove(filename)
# def copy_latest_files(source_dir, dest_dir, latest_files):
#     for filename in latest_files:
#         source_path = pathlib.Path(source_dir) / filename
#         dest_path = pathlib.Path(dest_dir) / filename
#         shutil.copy(source_path, dest_path)

# source_dir = f'{first_glob}/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/STORAGE_OUTPUT_RTA'
# dest_dir = f'{first_glob}/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/OUTPUT_RTA_FOR_REPORT'

# df = create_dataframe_with_filenames(source_dir)
# latest_files = get_latest_xlsx_files(df)
# delete_all_xlsx_files(dest_dir)
# copy_latest_files(source_dir, dest_dir, latest_files)