In [49]:
import pandas as pd
from datetime import date, timedelta
from datetime import datetime
import os
import shutil
import pathlib
from nbconvert import PythonExporter
import polars as pl
import glob
import time

In [50]:
def convert_to_datetime(struct_time):
    return datetime(*struct_time[:6])


def input_data(data_dir):
    """Read all xlsx/csv files in a directory into a single Polars DataFrame."""
    
    def read_file(filename):
        try:
            mtime = convert_to_datetime(time.localtime(os.path.getmtime(filename)))
            df = (pl.read_excel(filename, infer_schema_length=0) if filename.suffix.lower() == '.xlsx'
                  else pl.read_csv(filename, infer_schema_length=0,
                                   encoding='utf-8' if True else 'ISO-8859-1'))
            return df.with_columns(pl.lit(filename.stem).alias('sheet_name'),
                                   pl.lit(mtime).alias('Export time'))
        except Exception:
            try:
                return (pl.read_csv(filename, infer_schema_length=0,
                                    encoding='ISO-8859-1', ignore_errors=True)
                        .with_columns(pl.lit(filename.stem).alias('sheet_name'),
                                      pl.lit(mtime).alias('Export time')))
            except Exception as e:
                print(f"Error reading {filename}: {e}")
                return None

    dfs = [df for f in pathlib.Path(data_dir).glob('**/*.*')
           if f.suffix.lower() in ('.xlsx', '.csv') and (df := read_file(f)) is not None]
    
    if not dfs:
        return pl.DataFrame()

    col_dtypes = {col: {df[col].dtype for df in dfs if col in df.columns}
                  for col in set(col for df in dfs for col in df.columns)}
    dfs = [df.with_columns(pl.col(c).cast(pl.Utf8)
                           for c, t in col_dtypes.items() if c in df.columns and len(t) > 1)
           for df in dfs]

    return pl.concat(dfs, how='vertical')

In [51]:
notebook_dict = {
  'IEX_optimized.ipynb': 1,
  'RTA_optimized.ipynb': 1,
}

def convert_notebook(notebook_path):
    exporter = PythonExporter()
    output, _ = exporter.from_filename(notebook_path)
    return output

first_glob = os.path.expanduser("~").replace("\\", "/")
test_path  = f'{first_glob}/Concentrix Corporation'
if not os.path.exists(test_path):
    raise FileNotFoundError(f'Not found the path: {test_path}')

folder_paths = {
    'output_iex_base'     : f'{first_glob}/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/OUTPUT_AGENT_IEX_BASE'
}

print(f"Currently using base directory: {first_glob}")
IEX_BASE = input_data(folder_paths['output_iex_base'])
IEX_BASE

Currently using base directory: C:/Users/ADMIN

shape: (67_771, 10)
┌─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬────────┐
│ Agent   ┆ Date    ┆ Start_S ┆ End_Shi ┆ Schedul ┆ Start_A ┆ End_Act ┆ sheet_n ┆ Export  ┆ Genera │
│ ---     ┆ ---     ┆ hift    ┆ ft      ┆ ed Acti ┆ ction   ┆ ion     ┆ ame     ┆ time    ┆ te     │
│ str     ┆ str     ┆ ---     ┆ ---     ┆ vity    ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ Date   │
│         ┆         ┆ str     ┆ str     ┆ ---     ┆ str     ┆ str     ┆ str     ┆ datetim ┆ ---    │
│         ┆         ┆         ┆         ┆ str     ┆         ┆         ┆         ┆ e[μs]   ┆ str    │
╞═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪════════╡
│ Agent:  ┆ 2026-01 ┆ 9:00 PM ┆ 10:00   ┆ Break   ┆ 10:15   ┆ 10:30   ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -05     ┆         ┆ AM      ┆         ┆ PM      ┆ PM      ┆ e_2026_ ┆ -18 00: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 37:43   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 9:00 PM ┆ 10:00   ┆ Open    ┆ 10:30   ┆ 2:30 AM ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -05     ┆         ┆ AM      ┆ Time    ┆ PM      ┆         ┆ e_2026_ ┆ -18 00: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 37:43   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 9:00 PM ┆ 10:00   ┆ Lunch   ┆ 2:30 AM ┆ 3:30 AM ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -05     ┆         ┆ AM      ┆         ┆         ┆         ┆ e_2026_ ┆ -18 00: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 37:43   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 9:00 PM ┆ 10:00   ┆ Open    ┆ 3:30 AM ┆ 4:30 AM ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -05     ┆         ┆ AM      ┆ Time    ┆         ┆         ┆ e_2026_ ┆ -18 00: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 37:43   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 9:00 PM ┆ 10:00   ┆ Break   ┆ 4:30 AM ┆ 4:45 AM ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -05     ┆         ┆ AM      ┆         ┆         ┆         ┆ e_2026_ ┆ -18 00: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 37:43   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 9:00 PM ┆ 10:00   ┆ Open    ┆ 4:45 AM ┆ 6:00 AM ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -05     ┆         ┆ AM      ┆ Time    ┆         ┆         ┆ e_2026_ ┆ -18 00: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 37:43   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 9:00 PM ┆ 10:00   ┆ Extra   ┆ 6:00 AM ┆ 7:45 AM ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -05     ┆         ┆ AM      ┆ Hours   ┆         ┆         ┆ e_2026_ ┆ -18 00: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 37:43   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 9:00 PM ┆ 10:00   ┆ Break   ┆ 7:45 AM ┆ 8:00 AM ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -05     ┆         ┆ AM      ┆         ┆         ┆         ┆ e_2026_ ┆ -18 00: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 37:43   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 9:00 PM ┆ 10:00   ┆ Extra   ┆ 8:00 AM ┆ 10:00   ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -05     ┆         ┆ AM      ┆ Hours   ┆         ┆ AM      ┆ e_2026_ ┆ -18 00: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 37:43   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 9:00 PM ┆ 10:00   ┆ Open    ┆ 9:00 PM ┆ 10:15   ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -05     ┆         ┆ AM      ┆ Time    ┆         ┆ PM      ┆ e_2026_ ┆ -18 00: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 37:43   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 6:00 PM ┆ 7:00 AM ┆ Break   ┆ 10:15   ┆ 10:30   ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -06     ┆         ┆         ┆         ┆ PM      ┆ PM      ┆ e_2026_ ┆ -18 00: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 37:43   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 6:00 PM ┆ 7:00 AM ┆ Open    ┆ 10:30   ┆ 1:15 AM ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -06     ┆         ┆         ┆ Time    ┆ PM      ┆         ┆ e_2026_ ┆ -18 00: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 37:43   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 6:00 PM ┆ 7:00 AM ┆ Lunch   ┆ 1:15 AM ┆ 2:15 AM ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -06     ┆         ┆         ┆         ┆         ┆         ┆ e_2026_ ┆ -18 00: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 37:43   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 6:00 PM ┆ 7:00 AM ┆ Open    ┆ 2:15 AM ┆ 4:30 AM ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -06     ┆         ┆         ┆ Time    ┆         ┆         ┆ e_2026_ ┆ -18 00: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 37:43   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 6:00 PM ┆ 7:00 AM ┆ Break   ┆ 4:30 AM ┆ 4:45 AM ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -06     ┆         ┆         ┆         ┆         ┆         ┆ e_2026_ ┆ -18 00: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 37:43   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 6:00 PM ┆ 7:00 AM ┆ Open    ┆ 4:45 AM ┆ 6:00 AM ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -06     ┆         ┆         ┆ Time    ┆         ┆         ┆ e_2026_ ┆ -18 00: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 37:43   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 6:00 PM ┆ 7:00 AM ┆ Extra   ┆ 6:00 AM ┆ 7:00 AM ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -06     ┆         ┆         ┆ Hours   ┆         ┆         ┆ e_2026_ ┆ -18 00: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 37:43   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 6:00 PM ┆ 7:00 AM ┆ Extra   ┆ 6:00 PM ┆ 7:15 PM ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -06     ┆         ┆         ┆ Hours   ┆         ┆         ┆ e_2026_ ┆ -18 00: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 37:43   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 6:00 PM ┆ 7:00 AM ┆ Break   ┆ 7:15 PM ┆ 7:30 PM ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -06     ┆         ┆         ┆         ┆         ┆         ┆ e_2026_ ┆ -18 00: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 37:43   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 6:00 PM ┆ 7:00 AM ┆ Extra   ┆ 7:30 PM ┆ 9:00 PM ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -06     ┆         ┆         ┆ Hours   ┆         ┆         ┆ e_2026_ ┆ -18 00: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 37:43   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 6:00 PM ┆ 7:00 AM ┆ Open    ┆ 9:00 PM ┆ 10:15   ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -06     ┆         ┆         ┆ Time    ┆         ┆ PM      ┆ e_2026_ ┆ -18 00: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 37:43   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 8:30 PM ┆ 4:30 AM ┆ Break   ┆ 10:00   ┆ 10:15   ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -07     ┆         ┆         ┆         ┆ PM      ┆ PM      ┆ e_2026_ ┆ -18 00: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 37:43   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 8:30 PM ┆ 4:30 AM ┆ Extra   ┆ 10:15   ┆ 1:15 AM ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -07     ┆         ┆         ┆ Hours   ┆ PM      ┆         ┆ e_2026_ ┆ -18 00: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 37:43   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 8:30 PM ┆ 4:30 AM ┆ Break   ┆ 1:15 AM ┆ 1:30 AM ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -07     ┆         ┆         ┆         ┆         ┆         ┆ e_2026_ ┆ -18 00: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 37:43   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-01 ┆ 8:30 PM ┆ 4:30 AM ┆ Extra   ┆ 1:30 AM ┆ 4:30 AM ┆ IEX_Bas ┆ 2026-05 ┆ 1/13/2 │
│ 3000182 ┆ -07     ┆         ┆         ┆ Hours   ┆         ┆         ┆ e_2026_ ┆ -18 00: ┆ 6 3:36 │
│ HOANG,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 01_05   ┆ 37:43   ┆ AM     │
│ THIPHUO ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ N…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ …       ┆ …       ┆ …       ┆ …       ┆ …       ┆ …       ┆ …       ┆ …       ┆ …       ┆ …      │
│ Agent:  ┆ 2026-05 ┆ 9:00 PM ┆ 6:00 AM ┆ Open    ┆ 4:30 AM ┆ 6:00 AM ┆ IEX_Bas ┆ 2026-05 ┆ 5/15/2 │
│ 3112809 ┆ -19     ┆         ┆         ┆ Time    ┆         ┆         ┆ e_2026_ ┆ -18 00: ┆ 6      │
│ Duong,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 05_18   ┆ 37:43   ┆ 12:34  │
│ ThiThuy ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ AM     │
│ D…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-05 ┆ 9:00 PM ┆ 6:00 AM ┆ Open    ┆ 9:00 PM ┆ 11:15   ┆ IEX_Bas ┆ 2026-05 ┆ 5/15/2 │
│ 3112809 ┆ -19     ┆         ┆         ┆ Time    ┆         ┆ PM      ┆ e_2026_ ┆ -18 00: ┆ 6      │
│ Duong,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 05_18   ┆ 37:43   ┆ 12:34  │
│ ThiThuy ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ AM     │
│ D…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-05 ┆ null    ┆ null    ┆ Off     ┆ null    ┆ null    ┆ IEX_Bas ┆ 2026-05 ┆ 5/15/2 │
│ 3112809 ┆ -20     ┆         ┆         ┆         ┆         ┆         ┆ e_2026_ ┆ -18 00: ┆ 6      │
│ Duong,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 05_18   ┆ 37:43   ┆ 12:34  │
│ ThiThuy ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ AM     │
│ D…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-05 ┆ null    ┆ null    ┆ Off     ┆ null    ┆ null    ┆ IEX_Bas ┆ 2026-05 ┆ 5/15/2 │
│ 3112809 ┆ -21     ┆         ┆         ┆         ┆         ┆         ┆ e_2026_ ┆ -18 00: ┆ 6      │
│ Duong,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 05_18   ┆ 37:43   ┆ 12:34  │
│ ThiThuy ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ AM     │
│ D…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-05 ┆ 9:00 PM ┆ 6:00 AM ┆ Break   ┆ 11:15   ┆ 11:30   ┆ IEX_Bas ┆ 2026-05 ┆ 5/15/2 │
│ 3112809 ┆ -22     ┆         ┆         ┆         ┆ PM      ┆ PM      ┆ e_2026_ ┆ -18 00: ┆ 6      │
│ Duong,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 05_18   ┆ 37:43   ┆ 12:34  │
│ ThiThuy ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ AM     │
│ D…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-05 ┆ 9:00 PM ┆ 6:00 AM ┆ Open    ┆ 11:30   ┆ 1:30 AM ┆ IEX_Bas ┆ 2026-05 ┆ 5/15/2 │
│ 3112809 ┆ -22     ┆         ┆         ┆ Time    ┆ PM      ┆         ┆ e_2026_ ┆ -18 00: ┆ 6      │
│ Duong,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 05_18   ┆ 37:43   ┆ 12:34  │
│ ThiThuy ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ AM     │
│ D…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-05 ┆ 9:00 PM ┆ 6:00 AM ┆ Lunch   ┆ 1:30 AM ┆ 2:30 AM ┆ IEX_Bas ┆ 2026-05 ┆ 5/15/2 │
│ 3112809 ┆ -22     ┆         ┆         ┆         ┆         ┆         ┆ e_2026_ ┆ -18 00: ┆ 6      │
│ Duong,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 05_18   ┆ 37:43   ┆ 12:34  │
│ ThiThuy ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ AM     │
│ D…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-05 ┆ 9:00 PM ┆ 6:00 AM ┆ Open    ┆ 2:30 AM ┆ 5:15 AM ┆ IEX_Bas ┆ 2026-05 ┆ 5/15/2 │
│ 3112809 ┆ -22     ┆         ┆         ┆ Time    ┆         ┆         ┆ e_2026_ ┆ -18 00: ┆ 6      │
│ Duong,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 05_18   ┆ 37:43   ┆ 12:34  │
│ ThiThuy ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ AM     │
│ D…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-05 ┆ 9:00 PM ┆ 6:00 AM ┆ Break   ┆ 5:15 AM ┆ 5:30 AM ┆ IEX_Bas ┆ 2026-05 ┆ 5/15/2 │
│ 3112809 ┆ -22     ┆         ┆         ┆         ┆         ┆         ┆ e_2026_ ┆ -18 00: ┆ 6      │
│ Duong,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 05_18   ┆ 37:43   ┆ 12:34  │
│ ThiThuy ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ AM     │
│ D…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-05 ┆ 9:00 PM ┆ 6:00 AM ┆ Trainin ┆ 5:30 AM ┆ 6:00 AM ┆ IEX_Bas ┆ 2026-05 ┆ 5/15/2 │
│ 3112809 ┆ -22     ┆         ┆         ┆ g       ┆         ┆         ┆ e_2026_ ┆ -18 00: ┆ 6      │
│ Duong,  ┆         ┆         ┆         ┆ Offline ┆         ┆         ┆ 05_18   ┆ 37:43   ┆ 12:34  │
│ ThiThuy ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ AM     │
│ D…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-05 ┆ 9:00 PM ┆ 6:00 AM ┆ Open    ┆ 9:00 PM ┆ 11:15   ┆ IEX_Bas ┆ 2026-05 ┆ 5/15/2 │
│ 3112809 ┆ -22     ┆         ┆         ┆ Time    ┆         ┆ PM      ┆ e_2026_ ┆ -18 00: ┆ 6      │
│ Duong,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 05_18   ┆ 37:43   ┆ 12:34  │
│ ThiThuy ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ AM     │
│ D…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-05 ┆ 9:00 PM ┆ 6:00 AM ┆ Break   ┆ 11:15   ┆ 11:30   ┆ IEX_Bas ┆ 2026-05 ┆ 5/15/2 │
│ 3112809 ┆ -23     ┆         ┆         ┆         ┆ PM      ┆ PM      ┆ e_2026_ ┆ -18 00: ┆ 6      │
│ Duong,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 05_18   ┆ 37:43   ┆ 12:34  │
│ ThiThuy ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ AM     │
│ D…      ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆        │
│ Agent:  ┆ 2026-05 ┆ 9:00 PM ┆ 6:00 AM ┆ Open    ┆ 11:30   ┆ 1:00 AM ┆ IEX_Bas ┆ 2026-05 ┆ 5/15/2 │
│ 3112809 ┆ -23     ┆         ┆         ┆ Time    ┆ PM      ┆         ┆ e_2026_ ┆ -18 00: ┆ 6      │
│ Duong,  ┆         ┆         ┆         ┆         ┆         ┆         ┆ 05_18   ┆ 37:43   ┆ 12:34  │
│ ThiThuy ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ AM     │

In [52]:
for nbook in notebook_dict:
    if notebook_dict[nbook] == 0:
        print(f"Not executing notebook {nbook}.")
        continue
        
    nbook_path = f'{first_glob}/Concentrix Corporation/WFM-Expedia-HCM - Branding files/BI_Task/CODE/Python_Code/{nbook}'
    
    if os.path.isfile(nbook_path):
        print(f"Running notebook: {nbook}")
        try:
            script = convert_notebook(nbook_path)
            exec(script)
        except Exception as e:
            print(f"Error running notebook: {nbook}")
            print(str(e))
    else:
        print(f"Error: Notebook {nbook} not found.")

Running notebook: IEX_optimized.ipynb
--- FULL FOLDER PATHS LIST ---
input_iex: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/INPUT_AGENT_IEX_FOR_REPORT
input_hc_master: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Headcount/HC Master Database - 2026.xlsx
output_iex: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/OUTPUT_AGENT_IEX_FOR_REPORT
output_iex_all: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/STORAGE_OUTPUT_AGENT_IEX
output_iex_intervals: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/OUTPUT_AGENT_IEX_INTERVALS
output_iex_base: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/OUTPUT_AGENT_IEX_BASE
hc_extend_by_month: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Headcount/HC Extend by Month
input_iex_schedule_adjustment: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/IEX Backdated Schedule Adjustment Log.xlsx

<string>:273: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
<string>:307: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.

✅ Exported 20 file(s) to 'C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/OUTPUT_AGENT_IEX_BASE':
   IEX_Base_2026_01_05.csv  (4050 rows)
   IEX_Base_2026_01_12.csv  (4063 rows)
   IEX_Base_2026_01_19.csv  (3906 rows)
   IEX_Base_2026_01_26.csv  (3727 rows)
   IEX_Base_2026_02_02.csv  (3738 rows)
   IEX_Base_2026_02_09.csv  (3619 rows)
   IEX_Base_2026_02_16.csv  (3682 rows)
   IEX_Base_2026_02_23.csv  (3032 rows)
   IEX_Base_2026_03_02.csv  (3208 rows)
   IEX_Base_2026_03_09.csv  (2498 rows)
   IEX_Base_2026_03_16.csv  (3008 rows)
   IEX_Base_2026_03_23.csv  (2994 rows)
   IEX_Base_2026_03_30.csv  (2669 rows)
   IEX_Base_2026_04_06.csv  (2573 rows)
   IEX_Base_2026_04_13.csv  (3197 rows)
   IEX_Base_2026_04_20.csv  (3372 rows)
   IEX_Base_2026_04_27.csv  (3151 rows)
   IEX_Base_2026_05_04.csv  (3800 rows)
   IEX_Base_2026_05_11.csv  (3493 rows)
   IEX_Base_2026_05_18.csv  (3981 rows)
Valid weeks found: ['2026-01-05', '2026-01-12', '2026-01-19', '2026-01-26', '2026-02-02', '2026-02-09', '2026-02-16', '2026-02-23', '2026-03-02', '2026-03-09', '2026-03-16', '2026-03-23', '2026-03-30', '2026-04-06', '2026-04-13', '2026-04-20', '2026-04-27', '2026-05-04', '2026-05-11', '2026-05-18']

<string>:358: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.

Rows after filter: 67761
Weeks retained: ['2026-01-05', '2026-01-12', '2026-01-19', '2026-01-26', '2026-02-02', '2026-02-09', '2026-02-16', '2026-02-23', '2026-03-02', '2026-03-09', '2026-03-16', '2026-03-23', '2026-03-30', '2026-04-06', '2026-04-13', '2026-04-20', '2026-04-27', '2026-05-04', '2026-05-11', '2026-05-18']

<string>:742: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.

Valid weeks: [Timestamp('2026-01-05 00:00:00'), Timestamp('2026-01-12 00:00:00'), Timestamp('2026-01-19 00:00:00'), Timestamp('2026-01-26 00:00:00'), Timestamp('2026-02-02 00:00:00'), Timestamp('2026-02-09 00:00:00'), Timestamp('2026-02-16 00:00:00'), Timestamp('2026-02-23 00:00:00'), Timestamp('2026-03-02 00:00:00'), Timestamp('2026-03-09 00:00:00'), Timestamp('2026-03-16 00:00:00'), Timestamp('2026-03-23 00:00:00'), Timestamp('2026-03-30 00:00:00'), Timestamp('2026-04-06 00:00:00'), Timestamp('2026-04-13 00:00:00'), Timestamp('2026-04-20 00:00:00'), Timestamp('2026-04-27 00:00:00'), Timestamp('2026-05-04 00:00:00'), Timestamp('2026-05-11 00:00:00'), Timestamp('2026-05-18 00:00:00')]
Running notebook: RTA_optimized.ipynb
--- FULL FOLDER PATHS LIST ---
input_iex_rawdata: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/INPUT_AGENT_IEX_FOR_REPORT
storage_iex_rawdata: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/STORAGE_INPUT_AGENT_IEX
input_agent_activity: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/INPUT_AGENT_ACTIVITY_FOR_REPORT
storage_agent_activity: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/STORAGE_INPUT_AGENT_ACTIVITY
input_iex: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/OUTPUT_AGENT_IEX_FOR_REPORT
input_iex_intervals: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/OUTPUT_AGENT_IEX_INTERVALS
input_pull_out: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Save/EXP Leave Management.xlsx
input_ramco_code: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/INPUT_RAMCO_CODE
input_ramco_ot: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/INPUT_OT_RAMCO_CODE
output_rta: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/OUTPUT_RTA_FOR_REPORT
output_rta_all: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/STORAGE_OUTPUT_RTA
rta_intervals_output: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/OUTPUT_AGENT_ACTIVITY_INTERVALS
ramco_output: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata
hc_extend_by_month: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Headcount/HC Extend by Month
resources: C:/Users/ADMIN/Concentrix Corporation/WFM-Expedia-HCM - Branding files/BI_Task/CODE/Resources

Could not determine dtype for column 43, falling back to string
Could not determine dtype for column 43, falling back to string
Could not determine dtype for column 43, falling back to string
Could not determine dtype for column 43, falling back to string
Could not determine dtype for column 43, falling back to string
Could not determine dtype for column 43, falling back to string
Could not determine dtype for column 43, falling back to string
Could not determine dtype for column 8, falling back to string
<string>:388: DeprecationWarning: `DataFrame.melt` is deprecated; use `DataFrame.unpivot` instead, with `index` instead of `id_vars` and `on` instead of `value_vars`

shape: (1_882, 7)
┌───────────┬────────────┬─────────┬───────┬───────────────┬──────────────┬────────────────────────┐
│ EID       ┆ Date       ┆ ot_type ┆ hours ┆ nsa_authorize ┆ ot_authorize ┆ ot_status              │
│ ---       ┆ ---        ┆ ---     ┆ ---   ┆ ---           ┆ ---          ┆ ---                    │
│ str       ┆ date       ┆ str     ┆ f64   ┆ str           ┆ str          ┆ str                    │
╞═══════════╪════════════╪═════════╪═══════╪═══════════════╪══════════════╪════════════════════════╡
│ 102871040 ┆ 2026-04-30 ┆ OT3.0X  ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs - Authorized) │
│ 102457937 ┆ 2025-09-02 ┆ OT3.9X  ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs - Authorized) │
│ 102871040 ┆ 2026-02-05 ┆ OT2.0X  ┆ 3.5   ┆ Authorized    ┆ Authorized   ┆ (3.5 hrs - Authorized) │
│ 103173195 ┆ 2026-05-05 ┆ OT1.5X  ┆ 2.0   ┆ Authorized    ┆ Authorized   ┆ (2.0 hrs - Authorized) │
│ 102477510 ┆ 2026-02-18 ┆ OT3.0X  ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs - Authorized) │
│ 102884064 ┆ 2026-03-03 ┆ OT1.5X  ┆ 1.0   ┆ Authorized    ┆ Authorized   ┆ (1.0 hrs - Authorized) │
│ 103293773 ┆ 2026-02-20 ┆ OT3.9X  ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs - Authorized) │
│ 103293766 ┆ 2026-05-01 ┆ OT3.9X  ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs - Authorized) │
│ 103173197 ┆ 2025-09-02 ┆ OT3.0X  ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs - Authorized) │
│ 103169814 ┆ 2026-01-07 ┆ OT2.0X  ┆ 1.5   ┆               ┆ Authorized   ┆ (1.5 hrs - Authorized) │
│ 103109357 ┆ 2026-01-13 ┆ OT1.5X  ┆ 1.0   ┆ Authorized    ┆ Authorized   ┆ (1.0 hrs - Authorized) │
│ 103109151 ┆ 2026-01-01 ┆ OT3.0X  ┆ 9.0   ┆               ┆ Authorized   ┆ (9.0 hrs - Authorized) │
│ 103169816 ┆ 2026-01-09 ┆ OT2.1X  ┆ 3.5   ┆               ┆ Authorized   ┆ (3.5 hrs - Authorized) │
│ 103171103 ┆ 2025-04-07 ┆ OT3.0X  ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs - Authorized) │
│ 103171002 ┆ 2025-09-01 ┆ OT3.0X  ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs - Authorized) │
│ 103293766 ┆ 2026-05-05 ┆ OT1.5X  ┆ 1.0   ┆ Authorized    ┆ Authorized   ┆ (1.0 hrs - Authorized) │
│ 102477422 ┆ 2026-02-19 ┆ OT3.0X  ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs - Authorized) │
│ 103082092 ┆ 2025-04-30 ┆ OT3.0X  ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs - Authorized) │
│ 103129414 ┆ 2025-04-30 ┆ OT3.0X  ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs - Authorized) │
│ 102369579 ┆ 2026-03-08 ┆ OT2.0X  ┆ 4.0   ┆               ┆ Authorized   ┆ (4.0 hrs - Authorized) │
│ 102173363 ┆ 2026-03-12 ┆ OT1.5X  ┆ 3.5   ┆               ┆ Authorized   ┆ (3.5 hrs - Authorized) │
│ 102517346 ┆ 2026-01-07 ┆ OT2.0X  ┆ 5.5   ┆               ┆ Authorized   ┆ (5.5 hrs - Authorized) │
│ 103305160 ┆ 2026-02-16 ┆ OT3.9X  ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs - Authorized) │
│ 102484482 ┆ 2026-03-19 ┆ OT1.5X  ┆ 3.0   ┆ Authorized    ┆ Authorized   ┆ (3.0 hrs - Authorized) │
│ 103028093 ┆ 2026-01-01 ┆ OT3.9X  ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs - Authorized) │
│ …         ┆ …          ┆ …       ┆ …     ┆ …             ┆ …            ┆ …                      │
│ 103293766 ┆ 2025-09-02 ┆ OT3.9X  ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs - Authorized) │
│ 103173212 ┆ 2025-09-01 ┆ OT3.0X  ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs - Authorized) │
│ 102484482 ┆ 2026-04-26 ┆ OT3.9X  ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs - Authorized) │
│ 103082385 ┆ 2025-04-30 ┆ OT3.0X  ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs - Authorized) │
│ 103101215 ┆ 2025-09-01 ┆ OT3.0X  ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs - Authorized) │
│ 103119654 ┆ 2025-09-01 ┆ OT3.0X  ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs - Authorized) │
│ 103293751 ┆ 2026-02-16 ┆ OT3.0X  ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs - Authorized) │
│ 103142092 ┆ 2025-05-01 ┆ OT3.0X  ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs - Authorized) │
│ 103145155 ┆ 2025-04-30 ┆ OT3.0X  ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs - Authorized) │
│ 103130518 ┆ 2025-04-07 ┆ OT3.0X  ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs - Authorized) │
│ 102482237 ┆ 2026-01-01 ┆ OT3.0X  ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs - Authorized) │
│ 103129357 ┆ 2025-04-30 ┆ OT3.0X  ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs - Authorized) │
│ 103109357 ┆ 2026-02-18 ┆ OT3.9X  ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs - Authorized) │
│ 103105143 ┆ 2025-07-03 ┆ OT2.0X  ┆ 1.0   ┆ Authorized    ┆ Authorized   ┆ (1.0 hrs - Authorized) │
│ 103294755 ┆ 2025-09-02 ┆ OT3.9X  ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs - Authorized) │
│ 103127938 ┆ 2025-04-30 ┆ OT3.0X  ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs - Authorized) │
│ 102502720 ┆ 2025-05-01 ┆ OT3.0X  ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs - Authorized) │
│ 102370785 ┆ 2025-05-01 ┆ OT3.0X  ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs - Authorized) │
│ 102369579 ┆ 2026-02-19 ┆ OT3.0X  ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs - Authorized) │
│ 103548841 ┆ 2026-05-01 ┆ OT3.0X  ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs - Authorized) │
│ 103304841 ┆ 2025-09-01 ┆ OT3.9X  ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs - Authorized) │
│ 103129359 ┆ 2025-04-30 ┆ OT3.0X  ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs - Authorized) │
│ 103082161 ┆ 2026-02-17 ┆ OT3.0X  ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs - Authorized) │
│ 102830253 ┆ 2026-02-16 ┆ OT3.9X  ┆ 8.0   ┆               ┆ Authorized   ┆ (8.0 hrs - Authorized) │
│ 102477510 ┆ 2026-01-11 ┆ OT2.0X  ┆ 5.5   ┆               ┆ Authorized   ┆ (5.5 hrs - Authorized) │
└───────────┴────────────┴─────────┴───────┴───────────────┴──────────────┴────────────────────────┘
shape: (5, 4)
┌────────┬───────────┬──────────────────────────┬────────────────────┐
│ Month  ┆ EID       ┆ employee_name            ┆ count_working_days │
│ ---    ┆ ---       ┆ ---                      ┆ ---                │
│ str    ┆ i64       ┆ str                      ┆ i32                │
╞════════╪═══════════╪══════════════════════════╪════════════════════╡
│ Apr-25 ┆ 101993774 ┆ HIEU THI TRAN            ┆ 22                 │
│ Apr-25 ┆ 102029874 ┆ THIEN THANH TOAN  TRUONG ┆ 20                 │
│ Apr-25 ┆ 102173363 ┆ THI NGOC BICH  TRAN      ┆ 23                 │
│ Apr-25 ┆ 102173384 ┆ HUU VINH  MAI            ┆ 22                 │
│ Apr-25 ┆ 102211178 ┆ THI QUYNH TRANG  NGUYEN  ┆ 22                 │
└────────┴───────────┴──────────────────────────┴────────────────────┘
[None, 'After Call Work', 'Available Chat', 'Available Phone', 'Break', 'Coaching', 'End of Shift', 'Login', 'Lunch', 'Not Ready', 'Offline', 'Outbound Call', 'Phone Talking', 'Restroom', 'System Issue', 'Team Meeting', 'Training']
shape: (132, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ Date_Conve ┆ Staff Hour ┆ Total      ┆ THT(In    ┆ Avail     ┆ Other Pro ┆ Non Produ ┆ Present   │
│ rted       ┆ (In Hours) ┆ Break (In  ┆ Hours)    ┆ Time(In   ┆ ductive   ┆ ctive Aux ┆ for Calcu │
│ ---        ┆ ---        ┆ Hours)     ┆ ---       ┆ Hours)    ┆ Aux(In    ┆ (In       ┆ lation    │
│ date       ┆ f64        ┆ ---        ┆ f64       ┆ ---       ┆ Hours)    ┆ Hours)    ┆ ---       │
│            ┆            ┆ f64        ┆           ┆ f64       ┆ ---       ┆ ---       ┆ u32       │
│            ┆            ┆            ┆           ┆           ┆ f64       ┆ f64       ┆           │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2026-01-05 ┆ 870.359225 ┆ 109.324353 ┆ 485.61549 ┆ 198.67493 ┆ 6.482992  ┆ 70.26145  ┆ 76        │
│            ┆            ┆            ┆ 7         ┆ 3         ┆           ┆           ┆           │
│ 2026-01-06 ┆ 689.848203 ┆ 87.083347  ┆ 327.49354 ┆ 199.06851 ┆ 18.614342 ┆ 57.588461 ┆ 71        │
│            ┆            ┆            ┆ 2         ┆ 1         ┆           ┆           ┆           │
│ 2026-01-07 ┆ 609.753161 ┆ 73.936717  ┆ 279.01452 ┆ 198.93525 ┆ 14.859453 ┆ 43.007217 ┆ 65        │
│            ┆            ┆            ┆ 5         ┆           ┆           ┆           ┆           │
│ 2026-01-08 ┆ 703.719044 ┆ 89.506675  ┆ 319.12671 ┆ 205.27990 ┆ 9.191122  ┆ 80.614625 ┆ 69        │
│            ┆            ┆            ┆ 7         ┆ 6         ┆           ┆           ┆           │
│ 2026-01-09 ┆ 802.103047 ┆ 102.393236 ┆ 283.24617 ┆ 322.06589 ┆ 7.614478  ┆ 86.783261 ┆ 78        │
│            ┆            ┆            ┆ 5         ┆ 7         ┆           ┆           ┆           │
│ 2026-01-10 ┆ 575.924481 ┆ 78.556058  ┆ 225.41509 ┆ 241.27174 ┆ 4.460294  ┆ 26.221289 ┆ 62        │
│            ┆            ┆            ┆ 2         ┆ 7         ┆           ┆           ┆           │
│ 2026-01-11 ┆ 478.68895  ┆ 63.17197   ┆ 174.99060 ┆ 215.38769 ┆ 5.564222  ┆ 19.574458 ┆ 52        │
│            ┆            ┆            ┆ 1         ┆ 8         ┆           ┆           ┆           │
│ 2026-01-12 ┆ 538.870646 ┆ 81.25861   ┆ 273.80990 ┆ 170.81182 ┆ 2.890013  ┆ 10.100299 ┆ 61        │
│            ┆            ┆            ┆ 4         ┆           ┆           ┆           ┆           │
│ 2026-01-13 ┆ 761.584727 ┆ 108.658392 ┆ 301.48648 ┆ 297.53875 ┆ 13.358326 ┆ 40.542772 ┆ 78        │
│            ┆            ┆            ┆           ┆ 7         ┆           ┆           ┆           │
│ 2026-01-14 ┆ 695.925991 ┆ 107.580035 ┆ 284.68375 ┆ 291.12898 ┆ 5.825443  ┆ 6.707777  ┆ 76        │
│            ┆            ┆            ┆           ┆ 6         ┆           ┆           ┆           │
│ 2026-01-15 ┆ 671.197204 ┆ 98.762883  ┆ 309.20608 ┆ 231.17535 ┆ 4.341083  ┆ 27.711802 ┆ 72        │
│            ┆            ┆            ┆ 1         ┆ 4         ┆           ┆           ┆           │
│ 2026-01-16 ┆ 727.627256 ┆ 102.61367  ┆ 344.81992 ┆ 257.51198 ┆ 3.588485  ┆ 19.093194 ┆ 74        │
│            ┆            ┆            ┆ 1         ┆ 6         ┆           ┆           ┆           │
│ 2026-01-17 ┆ 555.377948 ┆ 79.907526  ┆ 265.60758 ┆ 184.57488 ┆ 6.732187  ┆ 18.555766 ┆ 62        │
│            ┆            ┆            ┆ 4         ┆ 5         ┆           ┆           ┆           │
│ 2026-01-18 ┆ 341.988169 ┆ 40.624467  ┆ 180.83998 ┆ 79.944546 ┆ 3.119818  ┆ 37.459356 ┆ 36        │
│            ┆            ┆            ┆ 2         ┆           ┆           ┆           ┆           │
│ 2026-01-19 ┆ 599.62767  ┆ 85.834786  ┆ 299.44191 ┆ 194.79413 ┆ 11.059156 ┆ 8.497679  ┆ 65        │
│            ┆            ┆            ┆ 1         ┆ 7         ┆           ┆           ┆           │
│ 2026-01-20 ┆ 587.407768 ┆ 81.630612  ┆ 274.50144 ┆ 180.78023 ┆ 19.983333 ┆ 30.512142 ┆ 61        │
│            ┆            ┆            ┆ 2         ┆ 9         ┆           ┆           ┆           │
│ 2026-01-21 ┆ 591.098452 ┆ 88.202465  ┆ 317.77674 ┆ 162.66282 ┆ 14.547474 ┆ 7.908945  ┆ 66        │
│            ┆            ┆            ┆           ┆ 6         ┆           ┆           ┆           │
│ 2026-01-22 ┆ 680.50809  ┆ 97.087172  ┆ 377.03716 ┆ 150.69846 ┆ 19.275624 ┆ 36.409665 ┆ 71        │
│            ┆            ┆            ┆ 5         ┆ 4         ┆           ┆           ┆           │
│ 2026-01-23 ┆ 631.870226 ┆ 91.024624  ┆ 374.06372 ┆ 145.92144 ┆ 13.386835 ┆ 7.473593  ┆ 69        │
│            ┆            ┆            ┆ 6         ┆ 8         ┆           ┆           ┆           │
│ 2026-01-24 ┆ 479.951412 ┆ 67.326202  ┆ 277.94744 ┆ 104.41468 ┆ 10.930364 ┆ 19.33272  ┆ 52        │
│            ┆            ┆            ┆           ┆ 7         ┆           ┆           ┆           │
│ 2026-01-25 ┆ 476.034741 ┆ 66.003026  ┆ 223.29657 ┆ 169.78828 ┆ 11.1665   ┆ 5.780351  ┆ 57        │
│            ┆            ┆            ┆ 5         ┆ 8         ┆           ┆           ┆           │
│ 2026-01-26 ┆ 557.082967 ┆ 85.829355  ┆ 311.88786 ┆ 138.38485 ┆ 13.63944  ┆ 7.341451  ┆ 62        │
│            ┆            ┆            ┆ 4         ┆ 8         ┆           ┆           ┆           │
│ 2026-01-27 ┆ 505.095533 ┆ 78.722822  ┆ 283.92479 ┆ 126.66823 ┆ 8.746882  ┆ 7.032798  ┆ 57        │
│            ┆            ┆            ┆ 7         ┆ 3         ┆           ┆           ┆           │
│ 2026-01-28 ┆ 504.483593 ┆ 80.101257  ┆ 232.32136 ┆ 179.65314 ┆ 7.981907  ┆ 4.425918  ┆ 56        │
│            ┆            ┆            ┆ 7         ┆ 4         ┆           ┆           ┆           │
│ 2026-01-29 ┆ 521.285812 ┆ 81.158857  ┆ 238.80373 ┆ 181.98276 ┆ 15.279757 ┆ 4.060694  ┆ 58        │
│            ┆            ┆            ┆ 9         ┆ 5         ┆           ┆           ┆           │
│ …          ┆ …          ┆ …          ┆ …         ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2026-04-22 ┆ 213.340696 ┆ 32.274241  ┆ 115.49946 ┆ 48.546236 ┆ 14.179427 ┆ 2.841329  ┆ 26        │
│            ┆            ┆            ┆ 4         ┆           ┆           ┆           ┆           │
│ 2026-04-23 ┆ 231.165423 ┆ 33.382763  ┆ 106.30473 ┆ 64.602219 ┆ 13.089339 ┆ 13.786365 ┆ 28        │
│            ┆            ┆            ┆ 7         ┆           ┆           ┆           ┆           │
│ 2026-04-24 ┆ 243.535208 ┆ 37.103353  ┆ 148.74607 ┆ 41.985493 ┆ 13.081097 ┆ 2.619193  ┆ 28        │
│            ┆            ┆            ┆ 2         ┆           ┆           ┆           ┆           │
│ 2026-04-25 ┆ 295.737081 ┆ 45.038004  ┆ 159.62570 ┆ 79.946081 ┆ 8.57629   ┆ 2.551004  ┆ 35        │
│            ┆            ┆            ┆ 2         ┆           ┆           ┆           ┆           │
│ 2026-04-26 ┆ 281.03946  ┆ 42.841056  ┆ 97.315536 ┆ 133.84671 ┆ 2.745579  ┆ 4.290578  ┆ 32        │
│            ┆            ┆            ┆           ┆ 2         ┆           ┆           ┆           │
│ 2026-04-27 ┆ 214.735672 ┆ 31.847513  ┆ 80.543855 ┆ 97.505729 ┆ 3.601089  ┆ 1.237486  ┆ 24        │
│ 2026-04-28 ┆ 188.39665  ┆ 28.441039  ┆ 85.899485 ┆ 68.544025 ┆ 4.42332   ┆ 1.088781  ┆ 21        │
│ 2026-04-29 ┆ 250.752742 ┆ 36.034639  ┆ 115.58410 ┆ 92.174808 ┆ 3.254701  ┆ 3.704491  ┆ 28        │
│            ┆            ┆            ┆ 3         ┆           ┆           ┆           ┆           │
│ 2026-04-30 ┆ 189.892947 ┆ 29.909512  ┆ 109.24196 ┆ 49.255324 ┆ 0.000402  ┆ 1.485749  ┆ 21        │
│ 2026-05-01 ┆ 236.974103 ┆ 35.305772  ┆ 118.93998 ┆ 79.026879 ┆ 0.289986  ┆ 3.411482  ┆ 26        │
│            ┆            ┆            ┆ 3         ┆           ┆           ┆           ┆           │
│ 2026-05-02 ┆ 287.691492 ┆ 45.859511  ┆ 168.61242 ┆ 68.904456 ┆ 1.737824  ┆ 2.577279  ┆ 32        │
│            ┆            ┆            ┆ 2         ┆           ┆           ┆           ┆           │
│ 2026-05-03 ┆ 259.709312 ┆ 39.466936  ┆ 116.73292 ┆ 100.73236 ┆ 0.952564  ┆ 1.824524  ┆ 30        │
│            ┆            ┆            ┆ 3         ┆ 6         ┆           ┆           ┆           │
│ 2026-05-04 ┆ 419.131142 ┆ 52.993634  ┆ 240.58028 ┆ 94.281959 ┆ 14.121649 ┆ 17.15362  ┆ 45        │
│ 2026-05-05 ┆ 461.170045 ┆ 65.631287  ┆ 198.20216 ┆ 163.89101 ┆ 9.302167  ┆ 24.143413 ┆ 48        │
│            ┆            ┆            ┆ 4         ┆ 3         ┆           ┆           ┆           │
│ 2026-05-06 ┆ 466.264132 ┆ 62.215211  ┆ 198.16293 ┆ 148.78920 ┆ 20.663262 ┆ 36.433519 ┆ 47        │
│            ┆            ┆            ┆ 3         ┆ 7         ┆           ┆           ┆           │
│ 2026-05-07 ┆ 443.702019 ┆ 57.826574  ┆ 251.14411 ┆ 83.137968 ┆ 18.420387 ┆ 33.172976 ┆ 46        │
│            ┆            ┆            ┆ 3         ┆           ┆           ┆           ┆           │
│ 2026-05-08 ┆ 480.84833  ┆ 58.331465  ┆ 258.33105 ┆ 99.853539 ┆ 9.168865  ┆ 55.163404 ┆ 47        │
│            ┆            ┆            ┆ 7         ┆           ┆           ┆           ┆           │
│ 2026-05-09 ┆ 403.414645 ┆ 56.436324  ┆ 225.48621 ┆ 94.020202 ┆ 3.597835  ┆ 23.874074 ┆ 42        │
│ 2026-05-10 ┆ 366.709657 ┆ 37.823579  ┆ 182.11218 ┆ 103.32059 ┆ 0.520187  ┆ 42.93311  ┆ 37        │
│            ┆            ┆            ┆ 6         ┆ 5         ┆           ┆           ┆           │
│ 2026-05-11 ┆ 377.028058 ┆ 54.525911  ┆ 216.67169 ┆ 93.048247 ┆ 6.049974  ┆ 6.732234  ┆ 42        │
│            ┆            ┆            ┆ 3         ┆           ┆           ┆           ┆           │
│ 2026-05-12 ┆ 379.606224 ┆ 57.833674  ┆ 175.88286 ┆ 134.82485 ┆ 6.542399  ┆ 4.522429  ┆ 42        │
│            ┆            ┆            ┆ 6         ┆ 5         ┆           ┆           ┆           │
│ 2026-05-13 ┆ 356.112696 ┆ 52.091048  ┆ 163.54378 ┆ 127.11684 ┆ 4.555942  ┆ 8.805084  ┆ 40        │
│            ┆            ┆            ┆           ┆ 2         ┆           ┆           ┆           │
│ 2026-05-14 ┆ 234.388173 ┆ 35.360085  ┆ 155.52578 ┆ 37.782735 ┆ 3.245014  ┆ 2.474557  ┆ 27        │
│            ┆            ┆            ┆ 1         ┆           ┆           ┆           ┆           │
│ 2026-05-15 ┆ 372.785729 ┆ 53.177927  ┆ 234.92793 ┆ 58.688785 ┆ 20.824983 ┆ 5.166104  ┆ 42        │
│            ┆            ┆            ┆ 1         ┆           ┆           ┆           ┆           │
│ 2026-05-16 ┆ 44.586569  ┆ 2.016789   ┆ 36.85851  ┆ 4.168973  ┆ 0.00088   ┆ 1.541417  ┆ 30        │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘
['2026-01-05', '2026-01-12', '2026-01-19', '2026-01-26', '2026-02-02', '2026-02-09', '2026-02-16', '2026-02-23', '2026-03-02', '2026-03-09', '2026-03-16', '2026-03-23', '2026-03-30', '2026-04-06', '2026-04-13', '2026-04-20', '2026-04-27', '2026-05-04', '2026-05-11']
Bỏ qua RTA_REPORT tuần 2026-05-18 (spillover ca đêm Chủ Nhật).
Bỏ qua RTA_REPORT tuần None (spillover ca đêm Chủ Nhật).
Bỏ qua RTA_EXTEND tuần None.

In [53]:
def input_data(folder_path, sheet_name=None):
    file_paths = glob.glob(f"{folder_path}/*.xlsx") + glob.glob(f"{folder_path}/*.csv")
    df_list = []

    for file in file_paths:
        if file.endswith('.xlsx'):
            df = pl.read_excel(file, sheet_name=sheet_name, infer_schema_length=0)
        elif file.endswith('.csv'):
            try:
                df = pl.read_csv(file, encoding="utf-8", infer_schema_length=0)
            except:
                df = pl.read_csv(file, encoding="ISO-8859-1", ignore_errors=True, infer_schema_length=0)
        
        df = df.with_columns([
            pl.col(col).cast(pl.String) 
            for col in df.columns
        ])
        
        df_list.append(df)
    
    merged_df = pl.concat(df_list, how='vertical')

    return merged_df

In [54]:
pl.Config.set_tbl_rows(50)
pl.Config.set_tbl_cols(100)

def filter_shift_discrepancies(df_input) -> pl.DataFrame:
    if isinstance(df_input, pd.DataFrame):
        df = pl.from_pandas(df_input)
    else:
        df = df_input

    # Requirement 1: hc_actual != hc_present
    hc_mismatch_condition = (
        pl.col("hc_actual").cast(pl.Float64, strict=False).fill_null(0.0) != 
        pl.col("hc_present").cast(pl.Float64, strict=False).fill_null(0.0)
    )

    # Requirement 2: Target > 3.75 AND sum_productive <= 3
    productivity_condition = (
        (pl.col("Target").cast(pl.Float64, strict=False).fill_null(0.0) > 3.75) &
        (pl.col("sum_productive").cast(pl.Float64, strict=False).fill_null(0.0) <= 3.0)
    )

    # Exclude any LOB containing "Support" (e.g. "Support", "Support - Ops", etc.)
    lob_condition = ~pl.col("LOB").str.contains("Support", literal=True)

    # Exclude Training/Offline shifts, Off Phone Misc, and PO from Shift Tracking
    shift_condition = (
        (~pl.col("First Shift").is_in(["Training", "Offline"])) &
        (~pl.col("Shift Tracking").is_in(["Training Offline", "Off Phone Misc", "PO"]))
    )

    # Main filtering logic
    result = df.filter(
        (hc_mismatch_condition | productivity_condition) &
        lob_condition &
        shift_condition
    )

    if "Date_Converted" in result.columns:
        result = result.sort("Date_Converted")

    return result

RTA_REPORT_GENERATE = input_data(f'{first_glob}/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/STORAGE_OUTPUT_RTA')
print(RTA_REPORT_GENERATE.columns)

RTA_REPORT_GENERATE = RTA_REPORT_GENERATE.with_columns([
    pl.col('Date_Converted').str.slice(0, 10).str.strptime(pl.Date, format='%Y-%m-%d'),
    pl.col('Target').cast(pl.Float64), 
    pl.col('duration').cast(pl.Float64),
    pl.col('sum_productive').cast(pl.Float64),
    pl.col('start').str.strip_chars().str.to_datetime("%Y-%m-%d %H:%M:%S%.3f", strict=False),
    pl.col('end').str.strip_chars().str.to_datetime("%Y-%m-%d %H:%M:%S%.3f", strict=False)
])

RTA_REPORT_GENERATE = RTA_REPORT_GENERATE.filter(
    pl.col('duration').is_not_null() | (pl.col('Target') > 0)
)

RTA_REPORT_GENERATE = RTA_REPORT_GENERATE.with_columns([
    pl.col('Shift Tracking').cast(pl.Utf8).str.strip_chars(),
    pl.col('Open Time').cast(pl.Float64).fill_null(0.0), 
    pl.col('Extra Time').cast(pl.Float64).fill_null(0.0)    
])
 
RTA_REPORT_GENERATE = RTA_REPORT_GENERATE.with_columns([
    pl.when(pl.col('Shift Tracking') == 'HDL').then(0.5)
    .when(
        (pl.col('Shift Tracking').is_in(['PR','PR - OT','PO'])) & 
        ((pl.col('Open Time') > 0) | (pl.col('Extra Time') > 0))
    ).then(1.0)
    .when(
        (pl.col('Shift Tracking').is_in([
            'Training Offline', 'Sick Leave', 'Paid Leave', 'Billable Training'
        ])) & (pl.col('Open Time') == 0)
    ).then(1.0)
    .when(
        (pl.col('Shift Tracking') != 'HDL') & 
        (pl.col('Shift Tracking') != 'PR') & 
        (pl.col('Open Time') == 0)
    ).then(0.0)
    .otherwise(None)
    .alias('hc_present')
])
 
filtered_data = RTA_REPORT_GENERATE.select([
    'Date_Converted', 'Employee Name', 'LOB', 'Detail Status','IEX ID','First Shift','Shift Tracking', 
    'start', 'end','Target', 'duration', 'sum_productive','training-idle','Extra Time', 'hc_schedule',
    'hc_actual', 'hc_present'
])
filtered_data = filtered_data.with_columns([
    pl.col('hc_actual').cast(pl.Float64),
    pl.col('hc_present').cast(pl.Float64)
])
 
start_date = '2026-03-01'
end_date = '2026-03-31'
 
start_date_parsed = pl.lit(start_date).str.strptime(pl.Date, format='%Y-%m-%d')
end_date_parsed = pl.lit(end_date).str.strptime(pl.Date, format='%Y-%m-%d')
 
sorted_data = filtered_data.sort('Date_Converted')
filtered_data = sorted_data.filter((pl.col('Date_Converted') >= start_date_parsed) & (pl.col('Date_Converted') <= end_date_parsed))
 
filtered_data_pd = filtered_data.to_pandas()

filtered_data_1 = filter_shift_discrepancies(filtered_data)
filtered_data_1

['Year', 'Month', 'Week_Monday', 'Date_Converted', 'Employee Name', 'Email Id', 'OracleID', 'IEX ID', 'Target', 'Datetime_Fluctuate_Start_Shift', 'Datetime_Fluctuate_End_Shift', 'Fluctuate Shift', 'Datetime_First_Start_Shift', 'Datetime_First_End_Shift', 'First Shift', 'Alias', 'LOB', 'LOB_2', 'LOB_3', 'Supervisor Name', 'Wave', 'Detail Status', 'Status', 'Time_Of_Day', 'Open Time', 'Extra Time', 'Break Time', 'Lunch Time', 'Training', 'NCNS', 'AL', 'Unplanned', 'Planned', 'Roster Presented', 'Roster Scheduled', 'Night_Shift', 'Shift Tracking', 'OT Type', 'Combined OT Range', 'OT PreShift', 'OT PostShift', 'start', 'end', 'total_time_chat_handle', 'sum_productive', 'break', 'lunch', 'coaching-idle', 'training-idle', 'outbound-idle', 'break_count', 'other_status', 'over_break', 'over_lunch', 'exceed_break', 'duration', 'hc_actual', 'hc_schedule', 'time_late', 'time_leave', 'lateness', 'adherence_time', 'total_time_pull_out', 'ramco_marked', 'nsa_authorize', 'ot_authorize', 'hours', 'ot_status', 'ot_type', 'days_count', 'nm_group', 'nsa_group', 'ot_group']

shape: (11, 17)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ Dat ┆ Emp ┆ LOB ┆ Det ┆ IEX ┆ Fir ┆ Shi ┆ sta ┆ end ┆ Tar ┆ dur ┆ sum ┆ tra ┆ Ext ┆ hc_ ┆ hc_ ┆ hc_ │
│ e_C ┆ loy ┆ --- ┆ ail ┆ ID  ┆ st  ┆ ft  ┆ rt  ┆ --- ┆ get ┆ ati ┆ _pr ┆ ini ┆ ra  ┆ sch ┆ act ┆ pre │
│ onv ┆ ee  ┆ str ┆ Sta ┆ --- ┆ Shi ┆ Tra ┆ --- ┆ dat ┆ --- ┆ on  ┆ odu ┆ ng- ┆ Tim ┆ edu ┆ ual ┆ sen │
│ ert ┆ Nam ┆     ┆ tus ┆ str ┆ ft  ┆ cki ┆ dat ┆ eti ┆ f64 ┆ --- ┆ cti ┆ idl ┆ e   ┆ le  ┆ --- ┆ t   │
│ ed  ┆ e   ┆     ┆ --- ┆     ┆ --- ┆ ng  ┆ eti ┆ me[ ┆     ┆ f64 ┆ ve  ┆ e   ┆ --- ┆ --- ┆ f64 ┆ --- │
│ --- ┆ --- ┆     ┆ str ┆     ┆ str ┆ --- ┆ me[ ┆ ms] ┆     ┆     ┆ --- ┆ --- ┆ f64 ┆ str ┆     ┆ f64 │
│ dat ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ ms] ┆     ┆     ┆     ┆ f64 ┆ str ┆     ┆     ┆     ┆     │
│ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 202 ┆ NGU ┆ Lod ┆ Lod ┆ 308 ┆ 070 ┆ NCN ┆ 202 ┆ 202 ┆ 0.0 ┆ 9.2 ┆ 0.5 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 1.0 ┆ 0.0 │
│ 6-0 ┆ YEN ┆ gin ┆ gin ┆ 910 ┆ 0-1 ┆ S   ┆ 6-0 ┆ 6-0 ┆     ┆ 499 ┆ 889 ┆     ┆     ┆     ┆     ┆     │
│ 3-0 ┆ NGO ┆ g   ┆ g   ┆ 7   ┆ 600 ┆     ┆ 3-0 ┆ 3-0 ┆     ┆ 63  ┆ 91  ┆     ┆     ┆     ┆     ┆     │
│ 3   ┆ C   ┆     ┆ Pro ┆     ┆     ┆     ┆ 3   ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ SON ┆     ┆ duc ┆     ┆     ┆     ┆ 06: ┆ 16: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ tio ┆     ┆     ┆     ┆ 57: ┆ 12: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆ 09  ┆ 09  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ PHA ┆ Lod ┆ Lod ┆ 309 ┆ 220 ┆ HDL ┆ 202 ┆ 202 ┆ 3.7 ┆ 16. ┆ 11. ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 1.0 ┆ 0.5 │
│ 6-0 ┆ N   ┆ gin ┆ gin ┆ 211 ┆ 0-0 ┆     ┆ 6-0 ┆ 6-0 ┆ 5   ┆ 592 ┆ 035 ┆ 006 ┆     ┆     ┆     ┆     │
│ 3-0 ┆ DAT ┆ g   ┆ g   ┆ 4   ┆ 700 ┆     ┆ 3-0 ┆ 3-0 ┆     ┆ 724 ┆ 701 ┆ 905 ┆     ┆     ┆     ┆     │
│ 8   ┆ LOI ┆     ┆ Pro ┆     ┆     ┆     ┆ 8   ┆ 9   ┆     ┆     ┆     ┆ 555 ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ duc ┆     ┆     ┆     ┆ 22: ┆ 14: ┆     ┆     ┆     ┆ 725 ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ tio ┆     ┆     ┆     ┆ 20: ┆ 56: ┆     ┆     ┆     ┆ 097 ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆ 55  ┆ 28  ┆     ┆     ┆     ┆ 656 ┆     ┆     ┆     ┆     │
│ 202 ┆ BUI ┆ Lod ┆ Lod ┆ 305 ┆ 210 ┆ AL  ┆ 202 ┆ 202 ┆ 0.0 ┆ 9.7 ┆ 8.1 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 1.0 ┆ 0.0 │
│ 6-0 ┆ BA  ┆ gin ┆ gin ┆ 230 ┆ 0-0 ┆     ┆ 6-0 ┆ 6-0 ┆     ┆ 763 ┆ 309 ┆     ┆     ┆     ┆     ┆     │
│ 3-0 ┆ DUO ┆ g   ┆ g   ┆ 6   ┆ 600 ┆     ┆ 3-0 ┆ 3-0 ┆     ┆ 37  ┆ 75  ┆     ┆     ┆     ┆     ┆     │
│ 8   ┆ NG  ┆     ┆ Pro ┆     ┆     ┆     ┆ 9   ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ duc ┆     ┆     ┆     ┆ 04: ┆ 14: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ tio ┆     ┆     ┆     ┆ 51: ┆ 37: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆ 09  ┆ 44  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ NGU ┆ Lod ┆ Lod ┆ 309 ┆ 070 ┆ Ext ┆ 202 ┆ 202 ┆ 0.0 ┆ 11. ┆ 9.1 ┆ 0.0 ┆ 4.2 ┆ 1.0 ┆ 1.0 ┆ 0.0 │
│ 6-0 ┆ YEN ┆ gin ┆ gin ┆ 728 ┆ 0-0 ┆ ra  ┆ 6-0 ┆ 6-0 ┆     ┆ 091 ┆ 307 ┆     ┆ 5   ┆     ┆     ┆     │
│ 3-1 ┆ MIN ┆ g   ┆ g   ┆ 4   ┆ 430 ┆ Hou ┆ 3-1 ┆ 3-1 ┆     ┆ 497 ┆ 65  ┆     ┆     ┆     ┆     ┆     │
│ 2   ┆ H   ┆     ┆ Pro ┆     ┆     ┆ rs  ┆ 2   ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ NHA ┆     ┆ duc ┆     ┆     ┆     ┆ 21: ┆ 09: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ T   ┆     ┆ tio ┆     ┆     ┆     ┆ 55: ┆ 01: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆ 41  ┆ 11  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ LE  ┆ Non ┆ Non ┆ 308 ┆ 060 ┆ NCN ┆ 202 ┆ 202 ┆ 0.0 ┆ 3.2 ┆ 2.4 ┆ 0.4 ┆ 0.0 ┆ 1.0 ┆ 0.5 ┆ 0.0 │
│ 6-0 ┆ HOA ┆ _Lo ┆ Lod ┆ 532 ┆ 0-1 ┆ S   ┆ 6-0 ┆ 6-0 ┆     ┆ 506 ┆ 735 ┆ 360 ┆     ┆     ┆     ┆     │
│ 3-1 ┆ NG  ┆ dgi ┆ gin ┆ 1   ┆ 500 ┆     ┆ 3-1 ┆ 3-1 ┆     ┆ 52  ┆ 87  ┆ 505 ┆     ┆     ┆     ┆     │
│ 7   ┆ THA ┆ ng  ┆ g   ┆     ┆     ┆     ┆ 7   ┆ 7   ┆     ┆     ┆     ┆ 506 ┆     ┆     ┆     ┆     │
│     ┆ O   ┆     ┆ Pro ┆     ┆     ┆     ┆ 06: ┆ 09: ┆     ┆     ┆     ┆ 727 ┆     ┆     ┆     ┆     │
│     ┆ NGO ┆     ┆ duc ┆     ┆     ┆     ┆ 08: ┆ 23: ┆     ┆     ┆     ┆ 430 ┆     ┆     ┆     ┆     │
│     ┆ C   ┆     ┆ tio ┆     ┆     ┆     ┆ 09  ┆ 12  ┆     ┆     ┆     ┆ 6   ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ VI  ┆ Lod ┆ Lod ┆ 308 ┆ 220 ┆ PR  ┆ 202 ┆ 202 ┆ 7.5 ┆ 8.9 ┆ 0.0 ┆ 7.4 ┆ 0.0 ┆ 1.0 ┆ 1.0 ┆ 1.0 │
│ 6-0 ┆ LE  ┆ gin ┆ gin ┆ 907 ┆ 0-0 ┆     ┆ 6-0 ┆ 6-0 ┆     ┆ 041 ┆     ┆ 339 ┆     ┆     ┆     ┆     │
│ 3-2 ┆ HOA ┆ g   ┆ g   ┆ 1   ┆ 700 ┆     ┆ 3-2 ┆ 3-2 ┆     ┆ 29  ┆     ┆ 899 ┆     ┆     ┆     ┆     │
│ 0   ┆ I   ┆     ┆ Pro ┆     ┆     ┆     ┆ 0   ┆ 1   ┆     ┆     ┆     ┆ 359 ┆     ┆     ┆     ┆     │
│     ┆ ANH ┆     ┆ duc ┆     ┆     ┆     ┆ 22: ┆ 07: ┆     ┆     ┆     ┆ 809 ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ tio ┆     ┆     ┆     ┆ 25: ┆ 19: ┆     ┆     ┆     ┆ 03  ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆ 19  ┆ 33  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ NGU ┆ Lod ┆ Lod ┆ 311 ┆ 050 ┆ NCN ┆ 202 ┆ 202 ┆ 0.0 ┆ 4.1 ┆ 3.9 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 0.5 ┆ 0.0 │
│ 6-0 ┆ YEN ┆ gin ┆ gin ┆ 280 ┆ 0-1 ┆ S   ┆ 6-0 ┆ 6-0 ┆     ┆ 830 ┆ 171 ┆     ┆     ┆     ┆     ┆     │
│ 3-2 ┆ THI ┆ g   ┆ g   ┆ 4   ┆ 400 ┆     ┆ 3-2 ┆ 3-2 ┆     ┆ 96  ┆ 33  ┆     ┆     ┆     ┆     ┆     │
│ 2   ┆ THU ┆     ┆ Pro ┆     ┆     ┆     ┆ 2   ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ THU ┆     ┆ duc ┆     ┆     ┆     ┆ 09: ┆ 14: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ Y   ┆     ┆ tio ┆     ┆     ┆     ┆ 57: ┆ 08: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆ 48  ┆ 47  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ DUO ┆ Lod ┆ Lod ┆ 308 ┆ 060 ┆ Ext ┆ 202 ┆ 202 ┆ 0.0 ┆ 9.3 ┆ 9.0 ┆ 0.0 ┆ 3.0 ┆ 1.0 ┆ 1.0 ┆ 0.0 │
│ 6-0 ┆ NG  ┆ gin ┆ gin ┆ 916 ┆ 0-0 ┆ ra  ┆ 6-0 ┆ 6-0 ┆     ┆ 503 ┆ 182 ┆     ┆     ┆     ┆     ┆     │
│ 3-2 ┆ CON ┆ g   ┆ g   ┆ 3   ┆ 500 ┆ Hou ┆ 3-2 ┆ 3-2 ┆     ┆ 03  ┆ 89  ┆     ┆     ┆     ┆     ┆     │
│ 3   ┆ G   ┆     ┆ Pro ┆     ┆     ┆ rs  ┆ 3   ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ HOA ┆     ┆ duc ┆     ┆     ┆     ┆ 20: ┆ 06: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ NG  ┆     ┆ tio ┆     ┆     ┆     ┆ 54: ┆ 15: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆ 06  ┆ 07  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ TRA ┆ Lod ┆ Lod ┆ 308 ┆ 060 ┆ PR  ┆ 202 ┆ 202 ┆ 7.5 ┆ 4.0 ┆ 3.8 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 0.5 ┆ 1.0 │
│ 6-0 ┆ N   ┆ gin ┆ gin ┆ 785 ┆ 0-1 ┆     ┆ 6-0 ┆ 6-0 ┆     ┆ 473 ┆ 021 ┆     ┆     ┆     ┆     ┆     │
│ 3-2 ┆ THI ┆ g   ┆ g   ┆ 9   ┆ 500 ┆     ┆ 3-2 ┆ 3-2 ┆     ┆ 08  ┆ 4   ┆     ┆     ┆     ┆     ┆     │
│ 3   ┆ TUO ┆     ┆ Pro ┆     ┆     ┆     ┆ 3   ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ NG  ┆     ┆ duc ┆     ┆     ┆     ┆ 05: ┆ 09: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ VY  ┆     ┆ tio ┆     ┆     ┆     ┆ 51: ┆ 54: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆ 42  ┆ 32  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ NGU ┆ Non ┆ Non ┆ 308 ┆ 060 ┆ PR  ┆ 202 ┆ 202 ┆ 7.5 ┆ 4.4 ┆ 4.1 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 0.5 ┆ 1.0 │
│ 6-0 ┆ YEN ┆ _Lo ┆ Lod ┆ 917 ┆ 0-1 ┆     ┆ 6-0 ┆ 6-0 ┆     ┆ 537 ┆ 772 ┆     ┆     ┆     ┆     ┆     │
│ 3-2 ┆ DAN ┆ dgi ┆ gin ┆ 5   ┆ 500 ┆     ┆ 3-2 ┆ 3-2 ┆     ┆ 77  ┆ 44  ┆     ┆     ┆     ┆     ┆     │
│ 4   ┆ G   ┆ ng  ┆ g   ┆     ┆     ┆     ┆ 4   ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ KHO ┆     ┆ Pro ┆     ┆     ┆     ┆ 06: ┆ 10: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ A   ┆     ┆ duc ┆     ┆     ┆     ┆ 05: ┆ 32: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ tio ┆     ┆     ┆     ┆ 18  ┆ 31  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ TRA ┆ Lod ┆ Lod ┆ 309 ┆ Off ┆ Off ┆ 202 ┆ 202 ┆ 0.0 ┆ 5.3 ┆ 5.3 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.5 ┆ 0.0 │
│ 6-0 ┆ N   ┆ gin ┆ gin ┆ 330 ┆     ┆     ┆ 6-0 ┆ 6-0 ┆     ┆ 462 ┆ 138 ┆     ┆     ┆     ┆     ┆     │
│ 3-2 ┆ THI ┆ g   ┆ g   ┆ 6   ┆     ┆     ┆ 3-2 ┆ 3-2 ┆     ┆     ┆ 88  ┆     ┆     ┆     ┆     ┆     │
│ 7   ┆ LAN ┆     ┆ Pro ┆     ┆     ┆     ┆ 7   ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ HUO ┆     ┆ duc ┆     ┆     ┆     ┆ 18: ┆ 23: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ NG  ┆     ┆ tio ┆     ┆     ┆     ┆ 30: ┆ 51: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆ 25  ┆ 11  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [55]:
# ── FILTER IEX_BASE BY filtered_data_1 ───────────────────────────────────────

IEX_BASE_filtered = IEX_BASE.with_columns(
    pl.col("Agent").str.extract(r"Agent:\s*(\d+)", 1).alias("IEX_ID"),
    pl.col("Date").cast(pl.Utf8)
)
filter_keys = (
    filtered_data_1
    .select([
        pl.col("IEX ID").cast(pl.Utf8).alias("IEX_ID"),
        pl.col("Date_Converted").cast(pl.Utf8).alias("Date")
    ])
    .unique()
)
IEX_BASE_filtered = IEX_BASE_filtered.join(filter_keys, on=["IEX_ID", "Date"], how="semi")
IEX_BASE_filtered = IEX_BASE_filtered.with_columns(
    pl.col("Date").str.strptime(pl.Date, format="%Y-%m-%d", strict=False),
    pl.col("Generate Date").str.strptime(pl.Datetime, format="%m/%d/%y %I:%M %p", strict=False),
    pl.col("Start_Shift").str.strptime(pl.Time, format="%I:%M %p", strict=False),
    pl.col("End_Shift").str.strptime(pl.Time, format="%I:%M %p", strict=False),
    pl.lit(None).cast(pl.Utf8).alias("Scheduled Activity"),
    pl.lit(None).cast(pl.Utf8).alias("Start_Action"),
    pl.lit(None).cast(pl.Utf8).alias("End_Action"),
    pl.col("sheet_name").str.strip_chars('"').str.replace(r"IEX_Base_", "").alias("sheet_name")
).drop("IEX_ID").unique().sort("Date")

with pl.Config(tbl_rows=50, tbl_cols=20, fmt_str_lengths=100, tbl_width_chars=500):
    display(IEX_BASE_filtered)

shape: (11, 10)
┌───────────────────────────────────┬────────────┬─────────────┬───────────┬────────────────────┬──────────────┬────────────┬────────────┬─────────────────────┬─────────────────────┐
│ Agent                             ┆ Date       ┆ Start_Shift ┆ End_Shift ┆ Scheduled Activity ┆ Start_Action ┆ End_Action ┆ sheet_name ┆ Export time         ┆ Generate Date       │
│ ---                               ┆ ---        ┆ ---         ┆ ---       ┆ ---                ┆ ---          ┆ ---        ┆ ---        ┆ ---                 ┆ ---                 │
│ str                               ┆ date       ┆ time        ┆ time      ┆ str                ┆ str          ┆ str        ┆ str        ┆ datetime[μs]        ┆ datetime[μs]        │
╞═══════════════════════════════════╪════════════╪═════════════╪═══════════╪════════════════════╪══════════════╪════════════╪════════════╪═════════════════════╪═════════════════════╡
│ Agent: 3089107 Nguyen, NgocSon    ┆ 2026-03-03 ┆ 07:00:00    ┆ 16:00:00  ┆ null               ┆ null         ┆ null       ┆ 2026_03_02 ┆ 2026-05-18 00:37:43 ┆ 2026-03-10 02:52:00 │
│ Agent: 3092114 Phan, DatLoi       ┆ 2026-03-08 ┆ 22:00:00    ┆ 07:00:00  ┆ null               ┆ null         ┆ null       ┆ 2026_03_02 ┆ 2026-05-18 00:37:43 ┆ 2026-03-10 02:52:00 │
│ Agent: 3052306 BUI, BADUONG       ┆ 2026-03-08 ┆ 21:00:00    ┆ 06:00:00  ┆ null               ┆ null         ┆ null       ┆ 2026_03_02 ┆ 2026-05-18 00:37:43 ┆ null                │
│ Agent: 3097284 Nguyen, MinhNhat   ┆ 2026-03-12 ┆ 07:00:00    ┆ 07:00:00  ┆ null               ┆ null         ┆ null       ┆ 2026_03_09 ┆ 2026-05-18 00:37:43 ┆ 2026-03-17 03:22:00 │
│ Agent: 3085321 LE, HOANGTHAONGOC  ┆ 2026-03-17 ┆ 06:00:00    ┆ 15:00:00  ┆ null               ┆ null         ┆ null       ┆ 2026_03_16 ┆ 2026-05-18 00:37:43 ┆ 2026-03-22 03:25:00 │
│ Agent: 3089071 Vi, LeHoaiAnh      ┆ 2026-03-20 ┆ 22:00:00    ┆ 07:00:00  ┆ null               ┆ null         ┆ null       ┆ 2026_03_16 ┆ 2026-05-18 00:37:43 ┆ 2026-03-22 03:25:00 │
│ Agent: 3112804 Nguyen, ThiThuThuy ┆ 2026-03-22 ┆ 05:00:00    ┆ 14:00:00  ┆ null               ┆ null         ┆ null       ┆ 2026_03_16 ┆ 2026-05-18 00:37:43 ┆ null                │
│ Agent: 3087859 TRAN, THITUONGVY   ┆ 2026-03-23 ┆ 06:00:00    ┆ 15:00:00  ┆ null               ┆ null         ┆ null       ┆ 2026_03_23 ┆ 2026-05-18 00:37:43 ┆ 2026-04-07 03:41:00 │
│ Agent: 3089163 Duong, CongHoang   ┆ 2026-03-23 ┆ 06:00:00    ┆ 06:00:00  ┆ null               ┆ null         ┆ null       ┆ 2026_03_23 ┆ 2026-05-18 00:37:43 ┆ 2026-04-07 03:41:00 │
│ Agent: 3089175 Nguyen, DangKhoa   ┆ 2026-03-24 ┆ 06:00:00    ┆ 15:00:00  ┆ null               ┆ null         ┆ null       ┆ 2026_03_23 ┆ 2026-05-18 00:37:43 ┆ 2026-04-07 03:41:00 │
│ Agent: 3093306 Tran, ThiLanHuong  ┆ 2026-03-27 ┆ null        ┆ null      ┆ null               ┆ null         ┆ null       ┆ 2026_03_23 ┆ 2026-05-18 00:37:43 ┆ 2026-04-07 03:41:00 │
└───────────────────────────────────┴────────────┴─────────────┴───────────┴────────────────────┴──────────────┴────────────┴────────────┴─────────────────────┴─────────────────────┘

In [56]:
# def get_xlsx_filenames(data_dir):
#     xlsx_files = []
#     for filename in pathlib.Path(data_dir).glob('**/*.xlsx'):
#         xlsx_files.append(filename.name)
#     return xlsx_files
# def create_dataframe_with_filenames(data_dir):
#     xlsx_filenames = get_xlsx_filenames(data_dir)
#     df = pd.DataFrame(xlsx_filenames, columns=['Filename'])
#     return df
# def get_latest_xlsx_files(df):
#     df = df[df['Filename'].str.match(r'\d{4}-\d{2}-\d{2}\.xlsx')]
#     df['Date'] = pd.to_datetime(df['Filename'].str.replace('.xlsx', ''), format='%Y-%m-%d')
#     df_sorted = df.sort_values(by='Date', ascending=False)
#     latest_files = df_sorted.head(8)['Filename'].tolist()
#     return latest_files
# def delete_all_xlsx_files(directory):
#     for filename in pathlib.Path(directory).glob('*.xlsx'):
#         os.remove(filename)
# def copy_latest_files(source_dir, dest_dir, latest_files):
#     for filename in latest_files:
#         source_path = pathlib.Path(source_dir) / filename
#         dest_path = pathlib.Path(dest_dir) / filename
#         shutil.copy(source_path, dest_path)

# source_dir = f'{first_glob}/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/STORAGE_OUTPUT_RTA'
# dest_dir = f'{first_glob}/Concentrix Corporation/WFM-Expedia-HCM - Branding files/Rawdata/OUTPUT_RTA_FOR_REPORT'

# df = create_dataframe_with_filenames(source_dir)
# latest_files = get_latest_xlsx_files(df)
# delete_all_xlsx_files(dest_dir)
# copy_latest_files(source_dir, dest_dir, latest_files)